# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

User.destroy_all
puts "destroyed users"
user1 = User.create(username: "mwr", email: "mwr", password: "password", image: File.open('app/assets/images/kdf.jpg'))
user2 = User.create(username: "hal", email: "candycorn@gmail.com", password: "password", image: File.open('app/assets/images/kdf.jpg'))
user3 = User.create(username: "Kendall", email: "Ilovecatsforever!!!!!!@garbage.pail", password: "password", image: File.open('app/assets/images/kdf.jpg'))
user4 = User.create(username: "Frances", email: "Iamadog", password: "Iamadog", image: File.open('app/assets/images/kdf.jpg'))
user5 = User.create(username: "barn", email: "barn@barn.io", password: "barnaby", image: File.open('app/assets/images/kdf.jpg'))
user6 = User.create(username: "Zoh", email: "zoh@gmail.com", password: "gothypants", image: File.open('app/assets/images/kdf.jpg'))

Book.destroy_all
puts "destroyed books"
book1 = Book.create(title: "Elder Edda", author_name: "Snorri Sturluson", image: File.open('app/assets/images/elder_edda.jpg'), blurb: "The Poetic Edda comprises a treasure trove of mythic and spiritual verse holding an important place in Nordic culture, literature, and heritage. Its tales of strife and death form a repository, in poetic form, of Norse mythology and heroic lore, embodying both the ethical views and the cultural life of the North during the late heathen and early Christian times. Collected by an unidentified Icelander, probably during the twelfth or thirteenth century, The Poetic Edda was rediscovered in Iceland in the seventeenth century by Danish scholars. Even then its value as poetry, as a source of historical information, and as a collection of entertaining stories was recognized. This meticulous translation succeeds in reproducing the verse patterns, the rhythm, the mood, and the dignity of the original.")
book2 = Book.create(title: "Egil's Saga", author_name: "Snorri Sturluson", image: File.open('app/assets/images/Egil.jpg'), blurb: "Egil's Saga tells the story of the long and brutal life of tenth-century warrior-poet and farmer Egil Skallagrimsson: a morally ambiguous character who was at once the composer of intricately beautiful poetry, and a physical grotesque capable of staggering brutality. The saga recounts Egil's progression from youthful savagery to mature wisdom as he struggles to avenge his father's exile from Norway, defend his honour against the Norwegian King Erik Bloodaxe, and fight for the English King Athelstan in his battles against Scotland. Exploring issues as diverse as the question of loyalty, the power of poetry, and the relationship between two brothers who love the same woman, Egil's Saga is a fascinating depiction of a deeply human character.")
book3 = Book.create(title: "Icelandic Folklore and Fairytales", author_name: "Jon Arnason", image: File.open('app/assets/images/Icelandic_f_and__tales.jpg'))
book4 = Book.create(title: "Release It!", author_name: "Michael Nygard", image: File.open('app/assets/images/release_it.jpg'), blurb: "Whether it's in Java, .NET, or Ruby on Rails, getting your application ready to ship is only half the battle. Did you design your system to survivef a sudden rush of visitors from Digg or Slashdot? Or an influx of real world customers from 100 different countries? Are you ready for a world filled with flakey networks, tangled databases, and impatient users? If you're a developer and don't want to be on call for 3AM for the rest of your life, this book will help. In Release It!, Michael T. Nygard shows you how to design and architect your application for the harsh realities it will face. You'll learn how to design your application for maximum uptime, performance, and return on investment. Mike explains that many problems with systems today start with the design.")
book5 = Book.create(title: "SICP", author_name: "Gerald Jay Sussman and Hal Abelson", image: File.open('app/assets/images/SICP.jpg'), blurb: "Structure and Interpretation of Computer Programs has had a dramatic impact on computer science curricula over the past decade. This long-awaited revision contains changes throughout the text. There are new implementations of most of the major programming systems in the book, including the interpreters and compilers, and the authors have incorporated many small changes that reflect their experience teaching the course at MIT since the first edition was published. A new theme has been introduced that emphasizes the central role played by different approaches to dealing with time in computational models: objects with state, concurrent programming, functional programming and lazy evaluation, and nondeterministic programming. There are new example sections on higher-order procedures in graphics and on applications of stream processing in numerical programming, and many new exercises. In addition, all the programs have been reworked to run in any Scheme implementation that adheres to the IEEE standard.")
book6 = Book.create(title: "The Three Body Problem", author_name: "Cixin Liu", image: File.open('app/assets/images/three_body.jpg'), blurb: "The Three-Body Problem is the first chance for English-speaking readers to experience this multiple award winning phenomenon from China's most beloved science fiction author, Liu Cixin. Set against the backdrop of China's Cultural Revolution, a secret military project sends signals into space to establish contact with aliens. An alien civilization on the brink of destruction captures the signal and plans to invade Earth. Meanwhile, on Earth, different camps start forming, planning to either welcome the superior beings and help them take over a world seen as corrupt, or to fight against the invasion. The result is a science fiction masterpiece of enormous scope and vision.")
book7 = Book.create(title: "The Dark Forest", author_name: "Cixin Liu", image: File.open('app/assets/images/dark_forest.jpg'), blurb: "This is the second novel in \"Remembrance of Earth’s Past\", the near-future trilogy written by the China's multiple-award-winning science fiction author, Cixin Liu.
In The Dark Forest, Earth is reeling from the revelation of a coming alien invasion — four centuries in the future. The aliens' human collaborators have been defeated but the presence of the sophons, the subatomic particles that allow Trisolaris instant access to all human information, means that Earth's defense plans are exposed to the enemy. Only the human mind remains a secret.
This is the motivation for the Wallfacer Project, a daring plan that grants four men enormous resources to design secret strategies hidden through deceit and misdirection from Earth and Trisolaris alike. Three of the Wallfacers are influential statesmen and scientists but the fourth is a total unknown. Luo Ji, an unambitious Chinese astronomer and sociologist, is baffled by his new status. All he knows is that he's the one Wallfacer that Trisolaris wants dead.")
book8 = Book.create(title: "Apothegm of Diogenes", author_name: "Diogenes of Sinope", image: File.open('app/assets/images/default_book_cover.jpg'), blurb: "Diogenes the Cynic is famed for walking the streets with a lamp in daylight, looking for an honest man. His biting wit and eccentric behavior were legendary, and it was by means of his renowned aphorisms that his moral teachings were transmitted. He scorned the conventions of civilized life, and his ascetic lifestyle and caustic opinions informed the Cynic philosophy and later influenced Stoicism. This unique edition also covers his immediate successors, such as Crates, his wife Hipparchia, and the witty moral preacher Bion. The contrasting teachings of the Cyrenaic school, founded by Aristippos, a pleasure-loving friend of Socrates, complete the volume, together with a selection of apocryphal letters.
About the Series: For over 100 years Oxford World's Classics has made available the broadest spectrum of literature from around the globe. Each affordable volume reflects Oxford's commitment to scholarship, providing the most accurate text plus a wealth of other valuable features, including expert introductions by leading authorities, voluminous notes to clarify the text, up-to-date bibliographies for further study, and much more.")
book9 = Book.create(title: "Independent People", author_name: "Haldor Laxness", image: File.open('app/assets/images/independent_peeps.jpg'), blurb: "This magnificent novel—which secured for its author the 1955 Nobel Prize in Literature—is at last available to contemporary American readers. Although it is set in the early twentieth century, it recalls both Iceland's medieval epics and such classics as Sigrid Undset's Kristin Lavransdatter. And if Bjartur of Summerhouses, the book's protagonist, is an ordinary sheep farmer, his flinty determination to achieve independence is genuinely heroic and, at the same time, terrifying and bleakly comic.
Having spent eighteen years in humiliating servitude, Bjartur wants nothing more than to raise his flocks unbeholden to any man. But Bjartur's spirited daughter wants to live unbeholden to him. What ensues is a battle of wills that is by turns harsh and touching, elemental in its emotional intensity and intimate in its homely detail. Vast in scope and deeply rewarding, Independent People is a masterpiece.")
book10 = Book.create(title: "Death's End", author_name: "Cixin Liu", image: File.open('app/assets/images/deaths_end.jpg'), blurb: "With The Three-Body Problem, English-speaking readers got their first chance to experience the multiple-award-winning and bestselling Remembrance of Earth's Past trilogy by China's most beloved science fiction author, Cixin Liu. The Three-Body Problem was released to great acclaim including coverage in The New York Times and The Wall Street Journal and won the Hugo Award for Best SF Novel (2015). It was also named a finalist for the Nebula Award (2014) making it the first translated novel to be nominated for a major SF award since Italo Calvino's Invisible Cities in 1976.
 Now this epic trilogy concludes with Death's End. Half a century after the Doomsday Battle, the uneasy balance of Dark Forest Deterrence keeps the Trisolaran invaders at bay. Earth enjoys unprecedented prosperity due to the infusion of Trisolaran knowledge. With human science advancing daily and the Trisolarans adopting Earth culture, it seems that the two civilizations will soon be able to co-exist peacefully as equals without the terrible threat of mutually assured annihilation. But the peace has also made humanity complacent.
Cheng Xin, an aerospace engineer from the early 21st century, awakens from hibernation in this new age. She brings with her knowledge of a long-forgotten program dating from the beginning of the Trisolar Crisis and her very presence may upset the delicate balance between two worlds. Will humanity reach for the stars or die in its cradle?")
book11 = Book.create(title: "The Dwarf", author_name: "Pär Lagerkvist", image: File.open('app/assets/images/dwarf.jpg'), blurb: "\"I have noticed that sometimes I frighten people; what they really fear is themselves. They think it is I who scare them, but it is the dwarf within them, the ape-faced manlike being who sticks up his head from the depths of their souls.\"
Pär Lagerkvist's richly philosophical novel The Dwarf is an exploration of individual and social identity. The novel, set in a time when Italian towns feuded over the outcome of the last feud, centers on a social outcast, the court dwarf Piccoline. From his special vantage point Piccoline comments on the court's prurience and on political intrigue as the town is gripped by a siege. Gradually, Piccoline is drawn deeper and deeper into the conflict, and he inspires fear and hate around him as he grows to represent the fascination of the masses with violence.")
book12 = Book.create(title: "Under the Glacier", author_name: "Haldor Laxness", image: File.open('app/assets/images/under_glacier.jpg'), blurb: "Nobel laureate Halldór Laxness’s Under the Glacier is a one-of-a-kind masterpiece, a wryly provocative novel at once earthy and otherworldly. At its outset, the Bishop of Iceland dispatches a young emissary to investigate certain charges against the pastor at Sn?fells Glacier, who, among other things, appears to have given up burying the dead. But once he arrives, the emissary finds that this dereliction counts only as a mild eccentricity in a community that regards itself as the center of the world and where Creation itself is a work in progress. What is the emissary to make, for example, of the boarded-up church? What about the mysterious building that has sprung up alongside it? Or the fact that Pastor Primus spends most of his time shoeing horses? Or that his wife, Ua (pronounced “ooh-a,” which is what men invariably sputter upon seeing her), is rumored never to have bathed, eaten, or slept? Piling improbability on top of improbability, Under the Glacier overflows with comedy both wild and deadpan as it conjures a phantasmagoria as beguiling as it is profound.")
book13 = Book.create(title: "Flowers of Evil", author_name: "Charles Baudelaire", image: File.open('app/assets/images/flowers_of_evil.jpg'), blurb: "The greatest French poet of the 19th century, Baudelaire was also the first truly modem poet, and his direct and indirect influence on the literature of our time has been immeasurable. ")
book14 = Book.create(title: "Táin Bó Cúailnge", author_name: "Lost to Antiquity", image: File.open('app/assets/images/tain.jpg'), blurb: "The Táin Bó Cúailnge, centre-piece of the eighth-century Ulster cycle of heroic tales, is Ireland's nearest approach to a great epic. It tells the story of a great cattle-raid, the invasion of Ulster by the armies of Medb and Ailill, queen and king of Connacht, and their allies, seeking to carry off the great Brown Bull of Cúailnge. The hero of the tale is Cúchulainn, the Hound of Ulster, who resists the invaders single-handed, while Ulster's warriors lie sick.
Thomas Kinsella's presents a complete and living version of the story. His translation is based on the partial texts in two medieval manuscripts, with elements from other version, and adds a group of related stories which prepare for the action of the Táin.
Illustrated with brush drawings by Louis le Brocquy, this edition provides a combination of medieval epic and modern art.")
book15 = Book.create(title: "The Handmaid's Tale", author_name: "Margaret Atwood", image: File.open('app/assets/images/handmaid.jpg'), blurb: "Offred is a Handmaid in the Republic of Gilead. She may leave the home of the Commander and his wife once a day to walk to food markets whose signs are now pictures instead of words because women are no longer allowed to read. She must lie on her back once a month and pray that the Commander makes her pregnant, because in an age of declining births, Offred and the other Handmaids are valued only if their ovaries are viable. Offred can remember the years before, when she lived and made love with her husband, Luke; when she played with and protected her daughter; when she had a job, money of her own, and access to knowledge. But all of that is gone now...")
book16 = Book.create(title: "The Left Hand of Darkness", author_name: "Ursula K. Le Guin", image: File.open('app/assets/images/left_hand.jpg'), blurb: "A groundbreaking work of science fiction, The Left Hand of Darkness tells the story of a lone human emissary to Winter, an alien world whose inhabitants can choose -and change - their gender. His goal is to facilitate Winter's inclusion in a growing intergalactic civilization. But to do so he must bridge the gulf between his own views and those of the completely dissimilar culture that he encounters.

Embracing the aspects of psychology, society, and human emotion on an alien world, The Left Hand of Darkness stands as a landmark achievement in the annals of intellectual science fiction.")
book17 = Book.create(title: "Discourses on Livy", author_name: "Nicolo Machiavelli", image: File.open('app/assets/images/livy.jpg'), blurb: "Discourses on Livy is the founding document of modern republicanism, and Harvey C. Mansfield and Nathan Tarcov have provided the definitive English translation of this classic work. Faithful to the original Italian text, properly attentive to Machiavelli's idiom and subtlety of thought, it is eminently readable. With a substantial introduction, extensive explanatory notes, a glossary of key words, and an annotated index, the Discourses reveals Machiavelli's radical vision of a new science of politics, a vision of \"new modes and orders\" that continue to shape the modern ethos.")
book18 = Book.create(title: "The Political Thought of William of Ockham", author_name: "Arthur Stephen McGrade", image: File.open('app/assets/images/ockham.jpg'), blurb: "The English Franciscan, William of Ockham (c. 1285 1349), was one of the most important thinkers of the later middle ages. Summoned to Avignon in 1324 to answer charges of heresy, Ockham became convinced that Pope John XXII was himself a heretic in denying the complete poverty of Christ and the apostles and a tyrant in claiming supremacy over the Roman empire. Ockham's political writings were a result of these personal convictions, but also include systematic discourses on the basis and functions of spiritual and secular power as well as exhaustive discussions of Franciscan poverty and the general problem of papal heresy. Ockham emerges in this study as a man deeply committed to natural and Christian human rights, who found these fundamental values so seriously menaced in his time that their survival could be assured only by radical, even revolutionary, personal action and by a basic reworking of traditional political thought.")
book19 = Book.create(title: "Ramayana", author_name: "Vālmīki", image: File.open('app/assets/images/ramayana.jpg'), blurb: "Few works in world literature have inspired so vast an audience, in nations with radically different languages and cultures, as the Ramayana and Mahabharata, two Sanskrit verse epics written some 2,000 years ago. In Ramayana (written by a poet known to us as Valmiki), William Buck has retold the story of Prince Rama with all its nobility of spirit, courtly intrigue, heroic renunciation, fierce battles, and triumph of good over evil in a length and manner that will make the great Indian epics accessible to the contemporary reader. The same is true for the Mahabharata in its original Sanskrit, probably the longest Indian epic ever composed. It is the story of a dynastic struggle, between the Kurus and Pandavas, for land. In his introduction, Sanskritist B. A. van Nooten notes, \"Apart from William Buck\'s rendition [no other English version has] been able to capture the blend of religion and martial spirit that pervades the original epic.")
book20 = Book.create(title: "Kural", author_name: "Thiruvalluvar", image: File.open('app/assets/images/kural.jpg'), blurb: "elect couplets of Thirukkural are translated by Rajagopalachar")
book21 = Book.create(title: "Aghora: At the Left Hand of God", author_name: "Robert E. Svoboda", image: File.open('app/assets/images/aghora.jpg'), blurb: "Aghora: At the Left Hand of God is the first book in the Aghora trilogy. Written almost entirely in Vimalananda's own words, it presents events from his life, tenets of his philosophy, and highlights from his spiritual practices. Designed partly to shock and partly to comfort, but wholly as an offering to his Beloved, Aghora is as clear a picture as possible of a man who was a riddle wrapped up in an enigma. Vimalananda insisted that this book be published only after his demise, that he might be spared pursuit by those whose curiosity might be inflamed by some of the sensational events described within. He believed in devoting his all to the pursuit of the direct perception of Reality, and advised others to be similarly dedicated to attaining personal experience of God. To readers he offered this warning: \"Don\'t take anything I say as gospel truth. I am human, I make mistakes. Test on yourselves what I\'ve told you. Try it out, experience it, and then you will know whether or not I\'m telling you the truth.")
book23 = Book.create(title: "The Kalevala", author_name: "Elias Lönnrot", image: File.open('app/assets/images/kalevala.jpg'), blurb: "The national folk epic of Finland is here presented in an English translation that is both scholarly and eminently readable. The lyrical passages and poetic images, the wry humor, the tall-tale extravagance, and the homely realism of the 'Kalevala' come through with extraordinary effectiveness.")
book24 = Book.create(title: "The Deeds of God in .Rddhipur", author_name: "Mhaimbhat", image: File.open('app/assets/images/deeds_of_god.jpg'), blurb: "A dissertation")
book25 = Book.create(title: "Thinking, Fast and Slow", author_name: "Daniel Kahneman ", image: File.open('app/assets/images/fast_and_slow.jpg'), blurb: "In the highly anticipated Thinking, Fast and Slow, Kahneman takes us on a groundbreaking tour of the mind and explains the two systems that drive the way we think. System 1 is fast, intuitive, and emotional; System 2 is slower, more deliberative, and more logical. Kahneman exposes the extraordinary capabilities—and also the faults and biases—of fast thinking, and reveals the pervasive influence of intuitive impressions on our thoughts and behavior. The impact of loss aversion and overconfidence on corporate strategies, the difficulties of predicting what will make us happy in the future, the challenges of properly framing risks at work and at home, the profound effect of cognitive biases on everything from playing the stock market to planning the next vacation—each of these can be understood only by knowing how the two systems work together to shape our judgments and decisions.
Engaging the reader in a lively conversation about how we think, Kahneman reveals where we can and cannot trust our intuitions and how we can tap into the benefits of slow thinking. He offers practical and enlightening insights into how choices are made in both our business and our personal lives—and how we can use different techniques to guard against the mental glitches that often get us into trouble. Thinking, Fast and Slow will transform the way you think about thinking. ")
book26 = Book.create(title: "Crossing of Prouerbs: Crosse-answeres and Crosse-humours", author_name: "Nicholas Breton", image: File.open('app/assets/images/cross_proverbs.jpg'), blurb: "Self published vanity work.  A man 'crosses' proverbs.")
book27 = Book.create(title: "Mahabharata", author_name: "Krishna-Dwaipayana Vyasa", image: File.open('app/assets/images/mahab.jpg'), blurb: "Growing from an oral tradition of ballads based on historic events in India, the Mahabharata was passed down and extended through the centuries, becoming the longest poem ever written. R. K. Narayan provides a superb rendition in an abbreviated and elegant retelling of this great epic.")
book28 = Book.create(title: "Heimskringla", author_name: "Snorri Sturluson", image: File.open('app/assets/images/heimskringla.jpg'), blurb: "Great classic by Icelandic poet/chieftain chronicles the reigns of 16 high kings descended from the warrior-wizard god Odin. Major section on 15-year reign of Olav II Haraldson, patron saint of Norway. Based on earlier histories, oral traditions, plus new material by author, all presented with intelligence, warmth and objectivity. Over 130 illustrations and 5 maps.")
book29 = Book.create(title: "The Mabinogi", author_name: "Lost to Antiquity", image: File.open('app/assets/images/mabinogi.jpg'), blurb: "The Mabinogi remains one of the great classics of European literature. Its Four Branches are tales of heroism and heartbreak, of love and disloyalty, that for all their magic and mystery, remain rooted in the emotional realities and moral complexities of everyday life. They are also rooted in the very soil of Wales, in a landscape relatively unchanged since these tales were first told in the early Middle Ages. This new and faithful English translation of The Mabinogi features photographs of the locations and landscapes evoked by and specifically named in the text, reminding us of the timelessness and beauty of the stories and the land they inhabit.")
book30 = Book.create(title: "Popol Vuh", author_name: "Lost to Antiquity", image: File.open('app/assets/images/popol.jpg'), blurb: "Popol Vuh, the Quiché Mayan book of creation, isn't only the most important text in the native languages of the Americas, it's also an extraordinary document of the human imagination. It begins with the deeds of Mayan gods in the darkness of a primeval sea & ends with the radiant splendor of the Mayan lords who founded the Quiché kingdom in the Guatemalan highlands. Originally written in Mayan hieroglyphs, it was transcribed into the Roman alphabet in the 16th century. This new edition of Dennis Tedlock's unabridged, widely praised translation includes new notes & commentary, newly translated passages, newly deciphered hieroglyphs & over 40 new illustrations.")
book31 = Book.create(title: "Dune", author_name: "Frank Herbert", image: File.open('app/assets/images/dune.jpg'), blurb: "Set in the far future amidst a sprawling feudal interstellar empire where planetary dynasties are controlled by noble houses that owe an allegiance to the imperial House Corrino, Dune tells the story of young Paul Atreides (the heir apparent to Duke Leto Atreides and heir of House Atreides) as he and his family accept control of the desert planet Arrakis, the only source of the 'spice' melange, the most important and valuable substance in the cosmos. The story explores the complex, multi-layered interactions of politics, religion, ecology, technology, and human emotion as the forces of the empire confront each other for control of Arrakis.
Published in 1965, it won the Hugo Award in 1966 and the inaugural Nebula Award for Best Novel. Dune is frequently cited as the world's best-selling sf novel.")
book32 = Book.create(title: "American Gods", author_name: "Neil Gaiman", image: File.open('app/assets/images/american_gods.jpg'), blurb: "A storm is coming...

Locked behind bars for three years, Shadow did his time, quietly waiting for the magic day when he could return to Eagle Point, Indiana. A man no longer scared of what tomorrow might bring, all he wanted was to be with Laura, the wife he deeply loved, and start a new life.

But just days before his release, Laura and Shadow’s best friend are killed in an accident. With his life in pieces and nothing to keep him tethered, Shadow accepts a job from a beguiling stranger he meets on the way home, an enigmatic man who calls himself Mr. Wednesday. A trickster and rogue, Wednesday seems to know more about Shadow than Shadow does himself.

Life as Wednesday’s bodyguard, driver, and errand boy is far more interesting and dangerous than Shadow ever imagined—it is a job that takes him on a dark and strange road trip and introduces him to a host of eccentric characters whose fates are mysteriously intertwined with his own. Along the way Shadow will learn that the past never dies; that everyone, including his beloved Laura, harbors secrets; and that dreams, totems, legends, and myths are more real than we know. Ultimately, he will discover that beneath the placid surface of everyday life a storm is brewing—an epic war for the very soul of America—and that he is standing squarely in its path.")
book33 = Book.create(title: "Rakshasa's Ring", author_name: "Viśākhadatta ", image: File.open('app/assets/images/rakshasa.jpg'), blurb: "The final, benedictory stanza of this political drama may refer to Emperor Chandra Gupta II (r. c.376-415 CE). Other than this clue to the date of the author, all we know about him is that he came of a princely family, and would have had political experience. The play is set just after Alexander’s invasion of India (c.325 BCE) when the first Emperor Chandra Gupta seized the throne and founded the Maurya dynasty. The exemplary Rákshasa is the loyal exiled chief minister of the deposed dynasty. But his opponent, far from being the villain of the piece, is a kind of super-hero—the inhumanly competent ascetic Kautílya, to whom is ascribed India’s famous handbook for rulers, a precursor to Machiavelli. Kautílya struggles not to destroy Rákshasa but to win him over to be his successor as Chandra Gupta’s chief minister, so that he himself can retire from politics.")
book34 = Book.create(title: "Cain", author_name: "José Saramago", image: File.open('app/assets/images/cain.jpg'), blurb: "In this, his last novel, José Saramago daringly reimagines the characters and narratives of the Old Testament, recalling his provocative The Gospel According to Jesus Christ. His tale runs from the Garden of Eden, when God realizes he has forgotten to give Adam and Eve the gift of speech, to the moment when Noah's Ark lands on the dry peak of Ararat. Cain, the despised, the murderer, is Saramago's protagonist.

Condemned to wander forever after he kills his brother Abel, Cain makes his way through the world in the company of a personable donkey. He is a witness to and participant in the stories of Isaac and Abraham, the destruction of the Tower of Babel, Moses and the golden calf, the trials of Job. The rapacious Queen Lilith takes him as her lover. An old man with two sheep on a rope crosses his path. And again and again, Cain encounters a God whose actions seem callous, cruel, and unjust. He confronts Him, he argues with Him. \"And one thing we know for certain,\" Saramago writes, \"is that they continued to argue and are arguing still.\"

A startling book- sensual, funny- in all ways a fitting end to Saramago's extraordinary career.")
book35 = Book.create(title: "My Struggle: Book 1", author_name: "Karl Ove Knausgård", image: File.open('app/assets/images/struggle.jpg'), blurb: "My Struggle: Book One introduces American readers to the audacious, addictive, and profoundly surprising international literary sensation that is the provocative and brilliant six-volume autobiographical novel by Karl Ove Knausgaard. It has already been anointed a Proustian masterpiece and is the rare work of dazzling literary originality that is intensely, irresistibly readable. Unafraid of the big issues—death, love, art, fear—and yet committed to the intimate details of life as it is lived, My Struggle is an essential work of contemporary literature.")
book36 = Book.create(title: "We Have Always Lived in the Castle", author_name: "Shirley Jackson", image: File.open('app/assets/images/castle.jpg'), blurb: "Merricat Blackwood lives on the family estate with her sister Constance and her Uncle Julian. Not long ago there were seven Blackwoods—until a fatal dose of arsenic found its way into the sugar bowl one terrible night. Acquitted of the murders, Constance has returned home, where Merricat protects her from the curiosity and hostility of the villagers. Their days pass in happy isolation until cousin Charles appears. Only Merricat can see the danger, and she must act swiftly to keep Constance from his grasp.")
book37 = Book.create(title: "The Legitimacy of the Modern Age", author_name: "Hans Blumenberg", image: File.open('app/assets/images/legitimacy.jpg'), blurb: "In this major work, Blumenberg takes issue with Karl Lowith's well-known thesis that the idea of progress is a secularized version of Christian eschatology, which promises a dramatic intervention that will consummate the history of the world from outside. Instead, Blumenberg argues, the idea of progress always implies a process at work within history, operating through an internal logic that ultimately expresses human choices and is legitimized by human self-assertion, by man's responsibility for his own fate.")
book38 = Book.create(title: "Between Facts & Norms", author_name: "Jürgen Habermas", image: File.open('app/assets/images/facts_and_norms.jpg'), blurb: "\"[A] fascinating synthesis of Continental and Anglo-American legal theory. . . full of interesting insights, acute criticisms, and striking passages\".
-- Richard A. Posner, \"The New Republic\" In \"Between Facts and Norms\" Jürgen Habermas works out the legal and political implications of his \"Theory of Communicative Action\" (1981), bringing to fruition the project announced with his publication of \"The Structural Transformation of the Public Sphere\" in 1962. This new work is a major contribution to recent debates on the rule of law and the possibilities of democracy in postindustrial societies. It offers a sweeping, sociologically informed conceptualization of law and basic rights, a normative account of the rule of law and the constitutional state, an attempt to bridge normative and empirical approaches to democracy, and an account of the social context required for democracy. The work concludes with a bold proposal for a new paradigm of law that goes beyond the dichotomies that have afflicted modern political theory from its inception and that still underlie current controversies between so-called liberals and civic republicans.")
book39 = Book.create(title: "The Political Forms of Modern Society: Bureaucracy, Democracy, Totalitarianism", author_name: "Claude Lefort", image: File.open('app/assets/images/political_forms.jpg'), blurb: "Claude Lefort is one of the leading social and political theorists in France today. This anthology of his most important work published over the last four decades makes his writing widely accessible to an English-speaking audience for the first time. With exceptional skill Lefort combines the analysis of contemporary political events with a sensitivity to the history of political thought. His critical account of the development of bureaucracy and totalitarianism in the Soviet Union and Eastern Europe is a timely contribution to current debates about the nature and shortcomings of these societies. His incisive analyses of Marx's theory of history and concept of ideology provide the backdrop for a highly original account of the role of symbolism in modern societies. While critical of many traditional assumptions and doctrines, Lefort develops a political position based on a reappraisal of the idea of human rights and a reconsideration of what \"democracy\" means today.The Political Forms of Modern Society is a major contribution to contemporary social and political theory. The volume includes a substantial introduction that describes the context of Lefort's writings and highlights the central themes of his work.Claude Lefort teaches social and political theory at the Ecole des Hautes Etudes en Sciences Sociales, Paris. He was a founder, with Cornelius Castoriadis, of the influential independent journal of the left, Socialisme ou Barbarie. John B. Thompson is Lecturer in Sociology at the University of Cambridge.")
book40 = Book.create(title: "Economy and Society: An Outline of Interpretive Sociology", author_name: "Max Weber", image: File.open('app/assets/images/e_and_s.jpg'), blurb: "Max Weber's Economy and Society is the greatest sociological treatise written in this century. Published posthumously in Germany in the early 1920's, it has become a constitutive part of the modern sociological imagination. Economy and Society was the first strictly empirical comparison of social structures and normative orders in world-historical depth, containing the famous chapters on social action, religion, law, bureaucracy, charisma, the city, and the political community with its dimensions of class, status and power.

Economy and Status is Weber's only major treatise for an educated general public. It was meant to be a broad introduction, but in its own way it is the most demanding textbook yet written by a sociologist. The precision of its definitions, the complexity of its typologies and the wealth of its historical content make the work a continuos challenge at several levels of comprehension: for the advanced undergraduate who gropes for his sense of society, for the graduate student who must develop his own analytical skills, and for the scholar who must match wits with Weber.

When the long-awaited first complete English edition of Economy and Society was published in 1968, Arthur Stinchcombe wrote in the American Journal of Sociology: \"My answer to the question of whether people should still start their sociological intellectual biographies with Economy and Society is yes.\" Reinhard Bendix noted in the American Sociological Review that the \"publication of a compete English edition of Weber's most systematic work [represents] the culmination of a cultural transmission to the American setting...It will be a study-guide and compendium for years to come for all those interested in historical sociology and comparative study.\"

In a lengthy introduction, Guenther Roth traces the intellectual prehistory of Economy and Society, the gradual emergence of its dominant themes and the nature of its internal logic.

Mr. Roth is a Professor of Sociology at Columbia University. Mr. Wittich heads an economic research group at the United Nations. ")
book41 = Book.create(title: "All the King's Men", author_name: "Robert Penn Warren", image: File.open('app/assets/images/jack_burden.jpg'), blurb: "More than just a classic political novel, Warren’s tale of power and corruption in the Depression-era South is a sustained meditation on the unforeseen consequences of every human act, the vexing connectedness of all people and the possibility—it’s not much of one—of goodness in a sinful world. Willie Stark, Warren’s lightly disguised version of Huey Long, the onetime Louisiana strongman/governor, begins as a genuine tribune of the people and ends as a murderous populist demagogue. Jack Burden is his press agent, who carries out the boss’s orders, first without objection, then in the face of his own increasingly troubled conscience. And the politics? For Warren, that’s simply the arena most likely to prove that man is a fallen creature. Which it does.")
book42 = Book.create(title: "The Infinity Gauntlet ", author_name: "Jim Starlin", image: File.open('app/assets/images/infinity.jpg'), blurb: "For the dark Titan, Thanos, the Infinity Gauntlet was the Holy Grail, the ultimate prize to be coveted above all else. Now, on the edge of Armageddon and led by the mysterious Adam Warlock, Earth's super heroes join in a desperate attempt to thwart this nihilistic god's insane plunge into galactic self-destruction.")
book43 = Book.create(title: "The Silmarillion", author_name: "J. R. R. Tolkein", image: File.open('app/assets/images/Silmarillion.jpg'), blurb: "The story of the creation of the world and of the First Age, this is the ancient drama to which the characters in The Lord of the Rings look back and in whose events some of them, such as Elrond and Galadriel, took part. The three Silmarils were jewels created by Fëanor, most gifted of the Elves. Within them was imprisoned the Light of the Two Trees of Valinor before the Trees themselves were destroyed by Morgoth, the first Dark Lord. Thereafter, the unsullied Light of Valinor lived on only in the Silmarils, but they were seized by Morgoth and set in his crown, which was guarded in the impenetrable fortress of Angband in the north of Middle-earth. The Silmarillion is the history of the rebellion of Fëanor and his kindred against the gods, their exile from Valinor and return to Middle-earth, and their war, hopeless despite all their heroism, against the great Enemy.")
book44 = Book.create(title: "Neuromancer", author_name: "William Gibson", image: File.open('app/assets/images/neuromancer.jpg'), blurb: "The Matrix is a world within the world, a global consensus- hallucination, the representation of every byte of data in cyberspace . . .

Case had been the sharpest data-thief in the business, until vengeful former employers crippled his nervous system. But now a new and very mysterious employer recruits him for a last-chance run. The target: an unthinkably powerful artificial intelligence orbiting Earth in service of the sinister Tessier-Ashpool business clan. With a dead man riding shotgun and Molly, mirror-eyed street-samurai, to watch his back, Case embarks on an adventure that ups the ante on an entire genre of fiction.

Hotwired to the leading edges of art and technology, Neuromancer ranks with 1984 and Brave New World as one of the century's most potent visions of the future.")
book45 = Book.create(title: "Labyrinths: Selected Stories and Other Writings", author_name: "Jorge Luis Borges", image: File.open('app/assets/images/Labyrinths.jpg'), blurb: "Although his work has been restricted to the short story, the essay, and poetry, Jorge Luis Borges of Argentina is recognized all over the world as one of the most original and significant figures in modern literature. In his preface, Andre Maurois writes: \"Borges is a great writer who has composed only little essays or short narratives. Yet they suffice for us to call him great because of their wonderful intelligence, their wealth of invention, and their tight, almost mathematical style.\"

Labyrinths is a representative selection of Borges\' writing, some forty pieces drawn from various of his books published over the years. The translations are by Harriet de Onis, Anthony Kerrigan, and others, including the editors, who have provided a biographical and critical introduction, as well as an extensive bibliography.")
book46 = Book.create(title: "The Old Man and the Sea", author_name: "Ernest Hemingway", image: File.open('app/assets/images/old_man.jpg'), blurb: "It is the story of an old Cuban fisherman and his supreme ordeal: a relentless, agonizing battle with a giant marlin far out in the Gulf Stream. Using the simple, powerful language of a fable, Hemingway takes the timeless themes of courage in the face of defeat and personal triumph won from loss and transforms them into a magnificent twentieth-century classic.")
book47 = Book.create(title: "Immortal Lycanthropes", author_name: "Hal Johnson", image: File.open('app/assets/images/imortal.jpg'), blurb: "\"A shameful fact about humanity is that some people can be so ugly that no one will be friends with them. It is shameful that humans can be so cruel, and it is shameful that humans can be so ugly.\”
So begins the incredible story of Myron Horowitz, a disfigured thirteen-year-old just trying to fit in at his Pennsylvania school. When a fight with a bully leaves him unconscious and naked in the wreckage of the cafeteria, Myron discovers that he is an immortal lycanthrope—a were-mammal who can transform from human to animal. He also discovers that there are others like him, and many of them want Myron dead. “People will turn into animals,” says the razor-witted narrator of this tour-de-force, “and here come ancient secrets and rivers of blood.”")
book48 = Book.create(title: "The Plague", author_name: "Albert Camus", image: File.open('app/assets/images/plague.jpg'), blurb: "A gripping tale of human unrelieved horror, of survival and resilience, and of the ways in which humankind confronts death, The Plague is at once a masterfully crafted novel, eloquently understated and epic in scope, and a parable of ageless moral resonance, profoundly relevant to our times. In Oran, a coastal town in North Africa, the plague begins as a series of portents, unheeded by the people. It gradually becomes a omnipresent reality, obliterating all traces of the past and driving its victims to almost unearthly extremes of suffering, madness, and compassion.")
book49 = Book.create(title: "Moby Dick", author_name: "Herman Melville", image: File.open('app/assets/images/moby_dick.jpg'), blurb: "\'Call me Ishmael.\'
So begins Herman Melville's masterpiece, one of the greatest works of imagination in literary history. As Ishmael is drawn into Captain Ahab's obsessive quest to slay the white whale Moby-Dick, he finds himself engaged in a metaphysical struggle between good and evil. More than just a novel of adventure, more than an paean to whaling lore and legend, Moby-Dick is a haunting social commentary, populated by some of the most enduring characters in literature; the crew of the Pequod, from stern, Quaker First Mate Starbuck, to the tattooed Polynesian harpooner Queequeg, are a vision of the world in microcosm, the pinnacle of Melville's lifelong meditation on America. Written with wonderfully redemptive humour, Moby-Dick is a profound, poetic inquiry into character, faith, and the nature of perception.
Based on the Northwestern University Press edition, this Penguin Classics edition includes a critical introduction by Andrew Delbanco, as well as valuable explanatory notes, maps, illustrations and a glossary of nautical terms.
Herman Melville is now regarded as one of America's greatest novelists. Much of the material for his novels was drawn from his own experience as a seaman aboard whaling ships. He wrote his masterpiece Moby-Dick in 1851, and died in 1891.")
book50 = Book.create(title: "Fearsome Creatures of the Lumberwoods: Twenty Chilling Tales from the Wilderness", author_name: "Hal Johnson", image: File.open('app/assets/images/fearsome.jpg'), blurb: "Just for kids, twenty bone-chilling tales about the most dangerous fantastical beasts in American folklore. Meet the Snoligoster, who feeds on the shadows of its victims. The Hodag, like a spiny-backed bull-horned rhinoceros. The Hoop Snake, which can chase prey at speeds of up to 60 miles per hour and then, with one sting of its tail, cause it to turn purple, swell up, and die.
Illustrated throughout, including eight drawings printed with glow-in-the-dark ink, Fearsome Creatures of the Lumberwoods is for every young reader who loves a good scare. The book was originally published in 1910 by William Thomas Cox and is now inspiringly retold by Hal Johnson, author of Immortal Lycanthropes. The creatures are all scales and claws, razor-sharp teeth and stealth, camouflage and single-minded nastiness. Straight out of the era of Paul Bunyan, they speak to an earlier time in American history, when the woods were indeed dark and deep and filled with mystery. The tone is smart and quirky. The illustrations have a sinewy, retro field-guide look. Read them around a campfire, if you dare.")

Review.destroy_all
review1 = Review.create(book_id: book1.id, user_id: user1.id, title: "Sagely wisdom", body: "He's no Solomon, but the sayings of Odin have some pretty good gems.  Not the best telling of the Volsunga saga I've read.")
review2 = Review.create(book_id: book1.id, user_id: user2.id, title: "I love the norse", body: "Title says it all")
review2 = Review.create(book_id: book2.id, user_id: user2.id, title: "I'm sorry; it's gross", body: "Gutter humor all the way down.  Don't get me wrong, it's very clever gutter humor.  Still, ick.")
review3 = Review.create(book_id: book2.id, user_id: user1.id, title: "My favorite Saga", body: "Seriously -- it's like someone wed Diogenes of Sinope and 80's action movie hero, wrapping the whole thing in the trappings of the medieval bardic tradition.  Everyone should read this book, and everyone should love this book.")
review4 = Review.create(book_id: book2.id, user_id: user5.id, title: "Good jokes by a bad poet", body: "Look, I get why Mike like this book so much.  I don't think it's the best, though.  It's up there.  One of the best.  But, Njal's is so much better.  4 out of 4 Barn's agree.")
review5 = Review.create(book_id: book14.id, user_id: user1.id, title: "A fun adventure", body: "There are some classic adventure tropes here.  I guess what I like most about this is how low the stakes are.  The whole thing is written with this epic scope, but it's just some guys stealing cows from their neighbors.  I mean, there's something humerous in that, right?")
review6 = Review.create(book_id: book14.id, user_id: user2.id, title: "Great pictures", body: "Man, this edition has some wonderful pictures.")
review7 = Review.create(book_id: book14.id, user_id: user6.id, title: "Maeve is awesome", body: "Seriously powerful woman queen starting (local) international incidents because her pride has been insulted.")
review8 = Review.create(book_id: book11.id, user_id: user1.id, title: "Ugh", body: "I like stories about the machinations of spiteful dwarves and the power they influence over kings as much as the next, but this is a little too close to home right now.")
review9 = Review.create(book_id: book11.id, user_id: user2.id, title: "Meh", body: "It was fine.")
review10 = Review.create(book_id: book11.id, user_id: user5.id, title: "What a weird book.", body: "Don't get me wrong, I think I like it.  I recommended it to a friend.  I just don't know why I like it.  It's so weird.")
review11 = Review.create(book_id: book4.id, user_id: user1.id, title: "Thanks, DM!", body: "I was building a rails app for a colleague and encountered a nasty race condition.  I complained about it to my spouse, and she talked to her boss who recommended this book to me.  Man, what a wonderful discussion of design practices, and the rationale behind them.  Clear and measured throughout.  I feel like I leveld up after reading this book.  Thanks, David!")
review12 = Review.create(book_id: book2.id, user_id: user3.id, title: "Boys!", body: "Why did I let myself get roped into reading this garbage.  I mean, they told me it was about a viking.  They way they talked about it didn't make it sound appeaing either.  But, they just wouldn't shut up.  So, I gave it a go.  I regret that.")
review13 = Review.create(book_id: book5.id, user_id: user6.id, title: "Lorem", body: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.")
review14 = Review.create(book_id: book5.id, user_id: user2.id, title: "Mathmatical!", body: "What a lovely introduction.  I enjoy the enthusiasm these two clearly have for the subject, and the wishful thinking approach to breaking down problems is really cool.  I did watch the lectures along with this book.  P.S. -- knowing Z, I'll bet she typed out that Lorem Ipsum herself!")
review15 = Review.create(book_id: book44.id, user_id: user1.id, title: "classic", body: "One weird thing, though -- the future as Gibson envisioned it was really pink.  Read the book again -- 82 times he says pink.  It's just pink plastic bubblegum.  It's vaporwave.")
review16 = Review.create(book_id: book44.id, user_id: user2.id, title: "Meh", body: "It's fine.  Overrated")
review17 = Review.create(book_id: book44.id, user_id: user3.id, title: "I agree with that guy!", body: "It's an okay book.  But, a bit boring.")
review18 = Review.create(book_id: book44.id, user_id: user4.id, title: "Woof!", body: "I'm a dog!  I don't read!  Who gave me an account.  Bark Bark Bark!  I don't like when my family reads--Let's go throw the toy around.")
review19 = Review.create(book_id: book44.id, user_id: user5.id, title: "It was a part of my childhood", body: "I can't judge it properly, but I am sad to see the extent to which Gibson got the future right.")
review20 = Review.create(book_id: book6.id, user_id: user6.id, title: "Hugo and Nebula in translation FTW", body: "This completely deserved to win both of these awards.  Amazing book.")
review20 = Review.create(book_id: book7.id, user_id: user2.id, title: "Game Theory", body: "One of the most innovative applications of game theory in modern Sci-Fi.")
review20 = Review.create(book_id: book7.id, user_id: user3.id, title: "Solid follow-up", body: "I didn't like it quite as much as the original, but I'm still in it for the long haul.")
review20 = Review.create(book_id: book7.id, user_id: user4.id, title: "It's a book", body: "I read it.  I'll read the next one.")
review20 = Review.create(book_id: book7.id, user_id: user6.id, title: "Too cynical", body: "The despairing view of the universe as a dark forest governed by mutual suspicion and a base drive to survive is bleak, and the author knows it.  At the same time, he doesn't seem to appreceate the possibility of beautiful actions, and meaning residing in that beauty itself.  He thinks that at the level of the species such actions are erradicated, and this is dreaful and despairing.")
review20 = Review.create(book_id: book8.id, user_id: user1.id, title: "A true hero", body: "Our modern age could take a lot from the wisdom of this 'dog.'  His insistence on frank speech and truth-telling could server our culture well. ")
review20 = Review.create(book_id: book8.id, user_id: user3.id, title: "What a jokester", body: "I know that most of the stories we have about this guy are just fabrications, but what fabrications!  A better troll than anyone on the internet today, and he did it with a purpose--to help others rather than to hurt them.  What a guy.")
review20 = Review.create(book_id: book8.id, user_id: user4.id, title: "No Cover", body: "I guess Diogenes himself would have scorned the cover of a book, so it's appropriate that this entry doesn't have one.")
review20 = Review.create(book_id: book9.id, user_id: user6.id, title: "I will date none who have not read this book.", body: "It is impossible to be cultured without knowing about Haldor.")
review20 = Review.create(book_id: book9.id, user_id: user2.id, title: "Good, not great.", body: "Not his best work.  Check out Under the Glaciar.")
review20 = Review.create(book_id: book9.id, user_id: user3.id, title: "Disturbing at places", body: "I like how he doesn't look down upon the 'salt of the earth' when writing about them.  Still, there are some very uncomfortable father-daughter moments.  Nice to see strong women in western world literature.")
review20 = Review.create(book_id: book10.id, user_id: user2.id, title: "Mind Blown", body: "It's like a Summa Science-fictionica.  Every 20 pages my mind was blown.  Also, the best possible (but still inadequate) secular response to the question of good and evil.  This guy is a modern Dostoyevsky.")
review20 = Review.create(book_id: book10.id, user_id: user3.id, title: "Best of the three", body: "Glad I stuck in for the long haul.  It was worth it.")
review20 = Review.create(book_id: book10.id, user_id: user4.id, title: "Aesthetic morality", body: "Like all intelligent folk who have inquired into the subject and not been driving mad or to nihilism, Cixin understands that rationality cannot render the world of this life meaningful.  The best rationality gets you is the bleak world of The Dark Forest.  Only an asethetic response will do.")
review20 = Review.create(book_id: book10.id, user_id: user5.id, title: "huh!", body: "Rarely does a book that addresses such weighty issues read so lightly!")
review20 = Review.create(book_id: book10.id, user_id: user6.id, title: "Not just Si Fi, it's true literature", body: "This book should get more press.  It could breath life back into the genre.")
review20 = Review.create(book_id: book11.id, user_id: user3.id, title: "Terrifying musings on human nature in the wake of the second world war", body: "I hope Par is wrong.")
review20 = Review.create(book_id: book11.id, user_id: user4.id, title: "I don't get it.", body: "I have been defeated.  I have friends that don't understand Scandenavian literature, and I pride myself in distinguishing myself from them.  That said, this book has vanquished me.  I just don't get it .  Why was it written.  What's the point and what's the message?")
review20 = Review.create(book_id: book12.id, user_id: user3.id, title: "Not his best", body: "Check out Indpendent People if you really want to understand this guy's reputation.")
review20 = Review.create(book_id: book12.id, user_id: user4.id, title: "My favorite", body: "The ghosts!")
review20 = Review.create(book_id: book12.id, user_id: user5.id, title: "Great jokes", body: "Funny dude.")
review20 = Review.create(book_id: book12.id, user_id: user6.id, title: "His crowning achievement", body: "This work balances perfectly Iceland's own trouble relationship with its pagan and christian heritage with references to the sagas, pastors dealing with questions of faith, real theological questions, and all with a great dollop of humor.  This is the work of a master of the craft at his prime.")
review20 = Review.create(book_id: book13.id, user_id: user3.id, title: "I like that he can find beauty in ugliness", body: "I mean, this guy is clearly getting some perverse pleasure out of subverting cultural norms, but it's still a good message.  We should look for beauty everywhere, and not reject anything or anyone.")
review20 = Review.create(book_id: book13.id, user_id: user4.id, title: "Gross", body: "This book should be banned.")
review20 = Review.create(book_id: book13.id, user_id: user5.id, title: "The first book of poetry I loved", body: "I didn't understand poetry until reading this.  Sure, I was a sullen teenager, but it opened my eyes to a bueauty I hadn't understood before.  Fin de siècle waas the best time.")
review20 = Review.create(book_id: book13.id, user_id: user6.id, title: "Warms my goth heart", body: "Chuck B was goth before goth was goth.")
review20 = Review.create(book_id: book14.id, user_id: user3.id, title: "Bridge between folklore and mythology", body: "It is really cool to see a longer tale, one tied up with the greater mythology of a people, incorperate so many trops from folklore.  This is a genre straddling work of the best sort.")
review20 = Review.create(book_id: book14.id, user_id: user4.id, title: "Interesting", body: "It's a book that has kind of a gross traditional depiction of 'manliness' sitting alongside very powerful women who are not vilified.  It's nice to see that these things are not mutually antagonistic.")
review20 = Review.create(book_id: book14.id, user_id: user5.id, title: "Woo!", body: "Heros that jump!")
review20 = Review.create(book_id: book15.id, user_id: user2.id, title: "Unrealistic", body: "We're not that awful, are we?  Could we ever really stoop this low?")
review20 = Review.create(book_id: book15.id, user_id: user3.id, title: "Scary", body: "Sometimes I feel like this is closer to reality than everyone would like to think.")
review20 = Review.create(book_id: book15.id, user_id: user4.id, title: "Distopian Literature at its best", body: "Distopian literature ought not to be what it has become.  Rather than simply describing a dark world, it ought to shine a light on trends in our current world that, if allowed to grow, could lead to disasterous consequences.  Gibson and Atwood both do this.  Kids these days, with their \"I'm Hungry Games\" do NOT know what they are missing.")




ReadStatus.destroy_all
readstatus1 = ReadStatus.create(user_id: user1.id, book_id:book1.id, status:"read")
readstatus2 = ReadStatus.create(user_id: user1.id, book_id:book2.id, status:"read")
readstatus3 = ReadStatus.create(user_id: user1.id, book_id:book3.id, status:"read")
readstatus4 = ReadStatus.create(user_id: user1.id, book_id:book4.id, status:"read")
readstatus5 = ReadStatus.create(user_id: user1.id, book_id:book5.id, status:"read")
readstatus6 = ReadStatus.create(user_id: user1.id, book_id:book6.id, status:"read")
readstatus7 = ReadStatus.create(user_id: user1.id, book_id:book7.id, status:"read")
readstatus8 = ReadStatus.create(user_id: user1.id, book_id:book8.id, status:"read")
readstatus9 = ReadStatus.create(user_id: user1.id, book_id:book9.id, status:"read")
readstatus10 = ReadStatus.create(user_id: user1.id, book_id:book10.id, status:"reading")
readstatus11 = ReadStatus.create(user_id: user1.id, book_id:book11.id, status:"reading")
readstatus12 = ReadStatus.create(user_id: user1.id, book_id:book12.id, status:"reading")
readstatus13 = ReadStatus.create(user_id: user1.id, book_id:book13.id, status:"reading")
readstatus14 = ReadStatus.create(user_id: user1.id, book_id:book14.id, status:"reading")
readstatus15 = ReadStatus.create(user_id: user1.id, book_id:book15.id, status:"to-read")
readstatus16 = ReadStatus.create(user_id: user1.id, book_id:book17.id, status:"to-read")
readstatus19 = ReadStatus.create(user_id: user5.id, book_id:book6.id, status:"reading")
readstatus20 = ReadStatus.create(user_id: user6.id, book_id:book15.id, status:"read")
readstatus21 = ReadStatus.create(user_id: user6.id, book_id:book4.id, status:"to-read")
readstatus22 = ReadStatus.create(user_id: user1.id, book_id:book5.id, status:"to-read")
readstatus23 = ReadStatus.create(user_id: user2.id, book_id:book13.id, status:"reading")
readstatus24 = ReadStatus.create(user_id: user2.id, book_id:book6.id, status:"read")
readstatus25 = ReadStatus.create(user_id: user2.id, book_id:book7.id, status:"reading")
readstatus26 = ReadStatus.create(user_id: user2.id, book_id:book10.id, status:"to-read")
readstatus27 = ReadStatus.create(user_id: user5.id, book_id:book1.id, status:"read")
readstatus28 = ReadStatus.create(user_id: user5.id, book_id:book2.id, status:"read")
readstatus29 = ReadStatus.create(user_id: user5.id, book_id:book12.id, status:"read")
readstatus30 = ReadStatus.create(user_id: user1.id, book_id:book18.id, status:"to-read")
readstatus31 = ReadStatus.create(user_id: user1.id, book_id:book19.id, status:"to-read")
readstatus32 = ReadStatus.create(user_id: user1.id, book_id:book20.id, status:"to-read")
readstatus33 = ReadStatus.create(user_id: user1.id, book_id:book21.id, status:"to-read")
readstatus35 = ReadStatus.create(user_id: user1.id, book_id:book23.id, status:"to-read")
readstatus36 = ReadStatus.create(user_id: user1.id, book_id:book24.id, status:"to-read")
readstatus37 = ReadStatus.create(user_id: user1.id, book_id:book25.id, status:"to-read")
readstatus38 = ReadStatus.create(user_id: user1.id, book_id:book26.id, status:"to-read")
readstatus39 = ReadStatus.create(user_id: user1.id, book_id:book27.id, status:"to-read")
readstatus40 = ReadStatus.create(user_id: user1.id, book_id:book28.id, status:"to-read")
readstatus41 = ReadStatus.create(user_id: user1.id, book_id:book29.id, status:"to-read")
readstatus42 = ReadStatus.create(user_id: user5.id, book_id:book8.id, status:"to-read")
readstatus43 = ReadStatus.create(user_id: user6.id, book_id:book8.id, status:"to-read")

Shelf.destroy_all
shelf1 = Shelf.create(user_id: user1.id, title: "Philosophy")
shelf2 = Shelf.create(user_id: user1.id, title: "IT")
shelf3 = Shelf.create(user_id: user1.id, title: "Sci-Fi")
shelf4 = Shelf.create(user_id: user1.id, title: "Iceland")
shelf5 = Shelf.create(user_id: user1.id, title: "Mythology")
shelf6 = Shelf.create(user_id: user1.id, title: "American")
shelf7 = Shelf.create(user_id: user1.id, title: "Poetry")
shelf8 = Shelf.create(user_id: user1.id, title: "Friends")
shelf9 = Shelf.create(user_id: user5.id, title: "music biography")
shelf10 = Shelf.create(user_id: user5.id, title: "nobels")
shelf17 = Shelf.create(user_id: user5.id, title: "Iceland" )
shelf18 = Shelf.create(user_id: user6.id, title: "Gothic Literature")
shelf19 = Shelf.create(user_id: user6.id, title: "Celtic Reconstruction")
shelf20 = Shelf.create(user_id: user6.id, title: "Feminist Literature")

ShelvedBook.destroy_all
shelvedbook1 = ShelvedBook.create(book_id: book17.id, shelf_id: shelf1.id)
shelvedbook1 = ShelvedBook.create(book_id: book18.id, shelf_id: shelf1.id)
shelvedbook1 = ShelvedBook.create(book_id: book38.id, shelf_id: shelf1.id)
shelvedbook1 = ShelvedBook.create(book_id: book39.id, shelf_id: shelf1.id)
shelvedbook1 = ShelvedBook.create(book_id: book40.id, shelf_id: shelf1.id)
shelvedbook1 = ShelvedBook.create(book_id: book1.id, shelf_id: shelf1.id)
shelvedbook4 = ShelvedBook.create(book_id: book2.id, shelf_id: shelf7.id)
shelvedbook5 = ShelvedBook.create(book_id: book3.id, shelf_id: shelf4.id)
shelvedbook6 = ShelvedBook.create(book_id: book4.id, shelf_id: shelf2.id)
shelvedbook7 = ShelvedBook.create(book_id: book5.id, shelf_id: shelf2.id)
shelvedbook8 = ShelvedBook.create(book_id: book6.id, shelf_id: shelf3.id)
shelvedbook9 = ShelvedBook.create(book_id: book7.id, shelf_id: shelf3.id)
shelvedbook10 = ShelvedBook.create(book_id: book10.id, shelf_id: shelf3.id)
shelvedbook11 = ShelvedBook.create(book_id: book8.id, shelf_id: shelf1.id)
shelvedbook12 = ShelvedBook.create(book_id: book9.id, shelf_id: shelf4.id)
shelvedbook15 = ShelvedBook.create(book_id: book12.id, shelf_id: shelf4.id)
shelvedbook17 = ShelvedBook.create(book_id: book14.id, shelf_id: shelf9.id)
shelvedbook18 = ShelvedBook.create(book_id: book15.id, shelf_id: shelf10.id)
shelvedbook18 = ShelvedBook.create(book_id: book16.id, shelf_id: shelf10.id)
shelvedbook18 = ShelvedBook.create(book_id: book16.id, shelf_id: shelf3.id)
shelvedbook18 = ShelvedBook.create(book_id: book31.id, shelf_id: shelf3.id)
shelvedbook18 = ShelvedBook.create(book_id: book44.id, shelf_id: shelf3.id)
shelvedbook15 = ShelvedBook.create(book_id: book1.id, shelf_id: shelf4.id)
shelvedbook15 = ShelvedBook.create(book_id: book2.id, shelf_id: shelf4.id)
shelvedbook15 = ShelvedBook.create(book_id: book1.id, shelf_id: shelf5.id)
shelvedbook15 = ShelvedBook.create(book_id: book2.id, shelf_id: shelf5.id)
shelvedbook15 = ShelvedBook.create(book_id: book3.id, shelf_id: shelf5.id)
shelvedbook15 = ShelvedBook.create(book_id: book14.id, shelf_id: shelf5.id)
shelvedbook15 = ShelvedBook.create(book_id: book23.id, shelf_id: shelf5.id)
shelvedbook15 = ShelvedBook.create(book_id: book24.id, shelf_id: shelf5.id)
shelvedbook15 = ShelvedBook.create(book_id: book27.id, shelf_id: shelf5.id)
shelvedbook15 = ShelvedBook.create(book_id: book28.id, shelf_id: shelf5.id)
shelvedbook15 = ShelvedBook.create(book_id: book29.id, shelf_id: shelf5.id)
shelvedbook15 = ShelvedBook.create(book_id: book30.id, shelf_id: shelf5.id)
shelvedbook15 = ShelvedBook.create(book_id: book43.id, shelf_id: shelf5.id)
shelvedbook15 = ShelvedBook.create(book_id: book31.id, shelf_id: shelf6.id)
shelvedbook15 = ShelvedBook.create(book_id: book32.id, shelf_id: shelf6.id)
shelvedbook15 = ShelvedBook.create(book_id: book36.id, shelf_id: shelf6.id)
shelvedbook15 = ShelvedBook.create(book_id: book41.id, shelf_id: shelf6.id)
shelvedbook15 = ShelvedBook.create(book_id: book46.id, shelf_id: shelf6.id)
shelvedbook15 = ShelvedBook.create(book_id: book49.id, shelf_id: shelf6.id)
shelvedbook15 = ShelvedBook.create(book_id: book20.id, shelf_id: shelf7.id)
shelvedbook15 = ShelvedBook.create(book_id: book23.id, shelf_id: shelf7.id)
shelvedbook15 = ShelvedBook.create(book_id: book13.id, shelf_id: shelf7.id)
shelvedbook15 = ShelvedBook.create(book_id: book47.id, shelf_id: shelf8.id)
shelvedbook15 = ShelvedBook.create(book_id: book50.id, shelf_id: shelf8.id)
