# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

User.destroy_all
puts "destroyed users"
user1 = User.create(username: "mwr", email: "mwr", password: "password", image: File.open('app/assets/images/kdf.jpg'))
user2 = User.create(username: "hal", email: "candycorn@gmail.com", password: "password", image: File.open('app/assets/images/kdf.jpg'))
user3 = User.create(username: "kendall", email: "Ilovecatsforever!!!!!!@garbage.pail", password: "password", image: File.open('app/assets/images/kdf.jpg'))
user4 = User.create(username: "mwr4", email: "mwr4", password: "password", image: File.open('app/assets/images/kdf.jpg'))
user5 = User.create(username: "barn", email: "barn@barn.io", password: "barnaby", image: File.open('app/assets/images/kdf.jpg'))
user6 = User.create(username: "zoh", email: "zoh@gmail.com", password: "gothypants", image: File.open('app/assets/images/kdf.jpg'))

Book.destroy_all
puts "destroyed books"
book1 = Book.create(title: "Elder Edda", author_name: "Snorri Sturluson", image: File.open('app/assets/images/elder_edda.jpg'))
book2 = Book.create(title: "Egil's Saga", author_name: "Snorri Sturluson", image: File.open('app/assets/images/Egil.jpg'))
book3 = Book.create(title: "Icelandic Folklore and Fairytales", author_name: "Jon Arnason", image: File.open('app/assets/images/Icelandic_f_and__tales.jpg'))
book4 = Book.create(title: "Release It!", author_name: "Michael Nygard", image: File.open('app/assets/images/release_it.jpg'))
book5 = Book.create(title: "SICP", author_name: "Gerald Jay Sussman and Hal Abelson", image: File.open('app/assets/images/SICP.jpg'))
book6 = Book.create(title: "The Three Body Problem", author_name: "Cixin Liu", image: File.open('app/assets/images/three_body.jpg'))
book7 = Book.create(title: "The Dark Forest", author_name: "Cixin Liu", image: File.open('app/assets/images/dark_forest.jpg'))
book8 = Book.create(title: "Apothegm of Diogenes", author_name: "Diogenes of Sinope", image: File.open('app/assets/images/default_book_cover.jpg'))
book9 = Book.create(title: "Independent People", author_name: "Haldor Laxness", image: File.open('app/assets/images/independent_peeps.jpg'))
book10 = Book.create(title: "Death's End", author_name: "Cixin Liu", image: File.open('app/assets/images/deaths_end.jpg'))
book11 = Book.create(title: "The Dwarf", author_name: "Pär Lagerkvist", image: File.open('app/assets/images/dwarf.jpg'))
book12 = Book.create(title: "Under the Glacier", author_name: "Haldor Laxness", image: File.open('app/assets/images/under_glacier.jpg'))
book13 = Book.create(title: "Flowers of Evil", author_name: "Charles Baudelaire", image: File.open('app/assets/images/flowers_of_evil.jpg'))
book14 = Book.create(title: "Táin Bó Cúailnge", author_name: "Lost to Antiquity", image: File.open('app/assets/images/tain.jpg'))
book15 = Book.create(title: "The Handmaid's Tale", author_name: "Margaret Atwood", image: File.open('app/assets/images/handmaid.jpg'))
book16 = Book.create(title: "The Left Hand of Darkness", author_name: "Ursula K. Le Guin", image: File.open('app/assets/images/left_hand.jpg'))
book17 = Book.create(title: "Discourses on Livy", author_name: "Nicolo Machiavelli", image: File.open('app/assets/images/livy.jpg'))
book18 = Book.create(title: "The Political Thought of William of Ockham", author_name: "Arthur Stephen McGrade", image: File.open('app/assets/images/ockham.jpg'))
book19 = Book.create(title: "Ramayana", author_name: "Vālmīki", image: File.open('app/assets/images/ramayana.jpg'))
book20 = Book.create(title: "Kural", author_name: "Thiruvalluvar", image: File.open('app/assets/images/kural.jpg'))
book21 = Book.create(title: "Aghora: At the Left Hand of God", author_name: "Robert E. Svoboda", image: File.open('app/assets/images/aghora.jpg'))
# book22 = Book.create(title: "The Panchtantra", author_name: "Vishnu Sharma", image: File.open('app/assets/images/panchatanra.jpg'))
book23 = Book.create(title: "The Kalevala", author_name: "Elias Lönnrot", image: File.open('app/assets/images/kalevala.jpg'))
book24 = Book.create(title: "The Deeds of God in .Rddhipur", author_name: "Mhaimbhat", image: File.open('app/assets/images/deeds_of_god.jpg'))
book25 = Book.create(title: "Thinking, Fast and Slow", author_name: "Daniel Kahneman ", image: File.open('app/assets/images/fast_and_slow.jpg'))
book26 = Book.create(title: "Crossing of Prouerbs: Crosse-answeres and Crosse-humours", author_name: "Nicholas Breton", image: File.open('app/assets/images/cross_proverbs.jpg'))
book27 = Book.create(title: "Mahabharata", author_name: "Krishna-Dwaipayana Vyasa", image: File.open('app/assets/images/mahab.jpg'))
book28 = Book.create(title: "Heimskringla", author_name: "Snorri Sturluson", image: File.open('app/assets/images/heimskringla.jpg'))
book29 = Book.create(title: "The Mabinogi", author_name: "Lost to Antiquity", image: File.open('app/assets/images/mabinogi.jpg'))
book30 = Book.create(title: "Popol Vuh", author_name: "Lost to Antiquity", image: File.open('app/assets/images/popol.jpg'))
book31 = Book.create(title: "Dune", author_name: "Frank Herbert", image: File.open('app/assets/images/dune.jpg'))
book32 = Book.create(title: "American Gods", author_name: "Neil Gaiman", image: File.open('app/assets/images/american_gods.jpg'))
book33 = Book.create(title: "Rakshasa's Ring", author_name: "Viśākhadatta ", image: File.open('app/assets/images/rakshasa.jpg'))
book34 = Book.create(title: "Cain", author_name: "José Saramago", image: File.open('app/assets/images/cain.jpg'))
book35 = Book.create(title: "My Struggle: Book 1", author_name: "Karl Ove Knausgård", image: File.open('app/assets/images/struggle.jpg'))
book36 = Book.create(title: "We Have Always Lived in the Castle", author_name: "Shirley Jackson", image: File.open('app/assets/images/castle.jpg'))
book37 = Book.create(title: "The Legitimacy of the Modern Age", author_name: "Hans Blumenberg", image: File.open('app/assets/images/legitimacy.jpg'))
book38 = Book.create(title: "Between Facts & Norms", author_name: "Jürgen Habermas", image: File.open('app/assets/images/facts_and_norms.jpg'))
book39 = Book.create(title: "The Political Forms of Modern Society: Bureaucracy, Democracy, Totalitarianism", author_name: "Claude Lefort", image: File.open('app/assets/images/political_forms.jpg'))
book40 = Book.create(title: "Economy and Society: An Outline of Interpretive Sociology", author_name: "Max Weber", image: File.open('app/assets/images/e_and_s.jpg'))
book41 = Book.create(title: "All the King's Men", author_name: "Robert Penn Warren", image: File.open('app/assets/images/jack_burden.jpg'))
book42 = Book.create(title: "The Infinity Gauntlet ", author_name: "Jim Starlin", image: File.open('app/assets/images/infinity.jpg'))
book43 = Book.create(title: "The Silmarillion", author_name: "William Gibson", image: File.open('app/assets/images/Silmarillion.jpg'))
book44 = Book.create(title: "Labyrinths: Selected Stories and Other Writings", author_name: "William Gibson", image: File.open('app/assets/images/neuromancer.jpg'))
book45 = Book.create(title: "Neuromancer", author_name: "Jorge Luis Borges", image: File.open('app/assets/images/Labyrinths.jpg'))
book46 = Book.create(title: "The Old Man and the Sea", author_name: "Ernest Hemingway", image: File.open('app/assets/images/old_man.jpg'))
book47 = Book.create(title: "Immortal Lycanthropes", author_name: "Hal Johnson", image: File.open('app/assets/images/imortal.jpg'))
book48 = Book.create(title: "The Plague", author_name: "Albert Camus", image: File.open('app/assets/images/plague.jpg'))
book49 = Book.create(title: "Moby Dick", author_name: "Herman Melville", image: File.open('app/assets/images/moby_dick.jpg'))
book50 = Book.create(title: "Fearsome Creatures of the Lumberwoods: Twenty Chilling Tales from the Wilderness", author_name: "Hal Johnson", image: File.open('app/assets/images/fearsome.jpg'))

ReadStatus.destroy_all
readstatus1 = ReadStatus.create(user_id: user1.id, book_id:book1.id, status:"read")
readstatus2 = ReadStatus.create(user_id: user1.id, book_id:book2.id, status:"read")
readstatus3 = ReadStatus.create(user_id: user1.id, book_id:book3.id, status:"read")
readstatus4 = ReadStatus.create(user_id: user1.id, book_id:book4.id, status:"read")
readstatus5 = ReadStatus.create(user_id: user1.id, book_id:book5.id, status:"read")
readstatus6 = ReadStatus.create(user_id: user1.id, book_id:book6.id, status:"read")
readstatus7 = ReadStatus.create(user_id: user1.id, book_id:book7.id, status:"read")
readstatus8 = ReadStatus.create(user_id: user1.id, book_id:book8.id, status:"read")
readstatus9 = ReadStatus.create(user_id: user1.id, book_id:book9.id, status:"read")
readstatus10 = ReadStatus.create(user_id: user1.id, book_id:book10.id, status:"read")
readstatus11 = ReadStatus.create(user_id: user1.id, book_id:book11.id, status:"read")
readstatus12 = ReadStatus.create(user_id: user1.id, book_id:book12.id, status:"read")
readstatus13 = ReadStatus.create(user_id: user1.id, book_id:book13.id, status:"read")
readstatus14 = ReadStatus.create(user_id: user1.id, book_id:book14.id, status:"read")
readstatus15 = ReadStatus.create(user_id: user1.id, book_id:book15.id, status:"read")
readstatus16 = ReadStatus.create(user_id: user1.id, book_id:book16.id, status:"read")
readstatus17 = ReadStatus.create(user_id: user5.id, book_id:book8.id, status:"to-read")
readstatus18 = ReadStatus.create(user_id: user6.id, book_id:book8.id, status:"to-read")
readstatus19 = ReadStatus.create(user_id: user5.id, book_id:book6.id, status:"reading")
readstatus20 = ReadStatus.create(user_id: user6.id, book_id:book15.id, status:"read")
readstatus21 = ReadStatus.create(user_id: user6.id, book_id:book4.id, status:"to-read")
readstatus22 = ReadStatus.create(user_id: user1.id, book_id:book5.id, status:"to-read")
readstatus23 = ReadStatus.create(user_id: user2.id, book_id:book13.id, status:"reading")
readstatus24 = ReadStatus.create(user_id: user2.id, book_id:book6.id, status:"read")
readstatus25 = ReadStatus.create(user_id: user2.id, book_id:book7.id, status:"reading")
readstatus26 = ReadStatus.create(user_id: user2.id, book_id:book10.id, status:"to-read")
readstatus27 = ReadStatus.create(user_id: user5.id, book_id:book1.id, status:"read")
readstatus28 = ReadStatus.create(user_id: user5.id, book_id:book2.id, status:"read")
readstatus29 = ReadStatus.create(user_id: user5.id, book_id:book12.id, status:"read")

Shelf.destroy_all
shelf1 = Shelf.create(user_id: user1.id, title: "philosophy")
shelf2 = Shelf.create(user_id: user1.id, title: "IT")
shelf3 = Shelf.create(user_id: user1.id, title: "Sci-Fi")
shelf4 = Shelf.create(user_id: user1.id, title: "Iceland")
shelf5 = Shelf.create(user_id: user5.id, title: "music biography")
shelf6 = Shelf.create(user_id: user5.id, title: "nobels")
shelf7 = Shelf.create(user_id: user5.id, title: "Iceland" )
shelf8 = Shelf.create(user_id: user6.id, title: "Gothic Literature")
shelf9 = Shelf.create(user_id: user6.id, title: "Celtic Reconstruction")
shelf10 = Shelf.create(user_id: user6.id, title: "Feminist Literature")

ShelvedBook.destroy_all
shelvedbook1 = ShelvedBook.create(book_id: book1.id, shelf_id: shelf1.id)
shelvedbook2 = ShelvedBook.create(book_id: book2.id, shelf_id: shelf2.id)
shelvedbook3 = ShelvedBook.create(book_id: book3.id, shelf_id: shelf3.id)
shelvedbook4 = ShelvedBook.create(book_id: book4.id, shelf_id: shelf4.id)
shelvedbook4 = ShelvedBook.create(book_id: book2.id, shelf_id: shelf7.id)
shelvedbook5 = ShelvedBook.create(book_id: book3.id, shelf_id: shelf4.id)
shelvedbook6 = ShelvedBook.create(book_id: book4.id, shelf_id: shelf2.id)
shelvedbook7 = ShelvedBook.create(book_id: book5.id, shelf_id: shelf2.id)
shelvedbook8 = ShelvedBook.create(book_id: book6.id, shelf_id: shelf3.id)
shelvedbook9 = ShelvedBook.create(book_id: book7.id, shelf_id: shelf3.id)
shelvedbook10 = ShelvedBook.create(book_id: book10.id, shelf_id: shelf3.id)
shelvedbook11 = ShelvedBook.create(book_id: book8.id, shelf_id: shelf1.id)
shelvedbook12 = ShelvedBook.create(book_id: book9.id, shelf_id: shelf4.id)
shelvedbook13 = ShelvedBook.create(book_id: book11.id, shelf_id: shelf6.id)
shelvedbook14 = ShelvedBook.create(book_id: book12.id, shelf_id: shelf6.id)
shelvedbook15 = ShelvedBook.create(book_id: book12.id, shelf_id: shelf4.id)
shelvedbook16 = ShelvedBook.create(book_id: book13.id, shelf_id: shelf8.id)
shelvedbook17 = ShelvedBook.create(book_id: book14.id, shelf_id: shelf9.id)
shelvedbook18 = ShelvedBook.create(book_id: book15.id, shelf_id: shelf10.id)
shelvedbook18 = ShelvedBook.create(book_id: book16.id, shelf_id: shelf10.id)
shelvedbook18 = ShelvedBook.create(book_id: book16.id, shelf_id: shelf3.id)

Review.destroy_all
review1 = Review.create(book_id: book1.id, user_id: user1.id, title: "Sagely wisdom", body: "He's no Solomon, but the sayings of Odin have some pretty good gems.  Not the best telling of the Volsunga saga I've read.")
review2 = Review.create(book_id: book1.id, user_id: user2.id, title: "I love the norse", body: "Title says it all")
review2 = Review.create(book_id: book2.id, user_id: user2.id, title: "I'm sorry it's gross", body: "but seriously -- this book has the best vomit scene in all of world history")
review3 = Review.create(book_id: book2.id, user_id: user1.id, title: "My favorite Saga", body: "Seriously -- it's like someone wed Diogenes of Sinope and 80's action movie hero, wrapping the whole thing in the trappings of the medieval bardic tradition.  Everyone should read this book, and everyone should love this book.")
review4 = Review.create(book_id: book2.id, user_id: user5.id, title: "Good jokes by a bad poet", body: "Don't get me wrong.  I get why Mike like this book so much.  I don't think it's the best, though.  It's up there.  One of the best.  But, Njal's is so much better")
review5 = Review.create(book_id: book14.id, user_id: user1.id, title: "A fun adventure", body: "There are some classic adventure tropes here.  I guess what I like most about this is how low the stakes are.  The whole thing is written with this epic scope, but it's just some guys stealing cows from their neighbors.  I mean, there's something humerous in that, right?")
review6 = Review.create(book_id: book14.id, user_id: user2.id, title: "Great pictures", body: "Man, this edition has some wonderful pictures.")
review7 = Review.create(book_id: book14.id, user_id: user6.id, title: "Maeve is awesome", body: "Badass woman queen starting (local) international incidents because her pride has been insulted.")
review8 = Review.create(book_id: book11.id, user_id: user1.id, title: "Ugh", body: "I like stories about the machinations of spiteful dwarves and the power they influence over kings as much as the next, but this is a little too close to home right now.")
review9 = Review.create(book_id: book11.id, user_id: user2.id, title: "Meh", body: "It was fine.")
review10 = Review.create(book_id: book11.id, user_id: user5.id, title: "What a weird book.", body: "Don't get me wrong, I think I like it.  I recommended it to a friend.  I just don't know why I like it.  It's so weird.")
