# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

User.destroy_all
puts "destroyed users"
user1 = User.create(username: "mwr", email: "mwr", password: "password", image: File.open('app/assets/images/kdf.jpg'))
user2 = User.create(username: "hal", email: "candycorn@gmail.com", password: "password", image: File.open('app/assets/images/kdf.jpg'))
user3 = User.create(username: "Kendall", email: "Ilovecatsforever!!!!!!@garbage.pail", password: "password", image: File.open('app/assets/images/kdf.jpg'))
user4 = User.create(username: "Frances", email: "Iamadog", password: "Iamadog", image: File.open('app/assets/images/kdf.jpg'))
user5 = User.create(username: "barn", email: "barn@barn.io", password: "barnaby", image: File.open('app/assets/images/kdf.jpg'))
user6 = User.create(username: "Zoh", email: "zoh@gmail.com", password: "gothypants", image: File.open('app/assets/images/kdf.jpg'))

Book.destroy_all
puts "destroyed books"
book1 = Book.create(title: "Elder Edda", author_name: "Snorri Sturluson", image: File.open('app/assets/images/elder_edda.jpg'), blurb: "The Poetic Edda comprises a treasure trove of mythic and spiritual verse holding an important place in Nordic culture, literature, and heritage. Its tales of strife and death form a repository, in poetic form, of Norse mythology and heroic lore, embodying both the ethical views and the cultural life of the North during the late heathen and early Christian times. Collected by an unidentified Icelander, probably during the twelfth or thirteenth century, The Poetic Edda was rediscovered in Iceland in the seventeenth century by Danish scholars. Even then its value as poetry, as a source of historical information, and as a collection of entertaining stories was recognized. This meticulous translation succeeds in reproducing the verse patterns, the rhythm, the mood, and the dignity of the original.")
book2 = Book.create(title: "Egil's Saga", author_name: "Snorri Sturluson", image: File.open('app/assets/images/Egil.jpg'), blurb: "Egil's Saga tells the story of the long and brutal life of tenth-century warrior-poet and farmer Egil Skallagrimsson: a morally ambiguous character who was at once the composer of intricately beautiful poetry, and a physical grotesque capable of staggering brutality. The saga recounts Egil's progression from youthful savagery to mature wisdom as he struggles to avenge his father's exile from Norway, defend his honour against the Norwegian King Erik Bloodaxe, and fight for the English King Athelstan in his battles against Scotland. Exploring issues as diverse as the question of loyalty, the power of poetry, and the relationship between two brothers who love the same woman, Egil's Saga is a fascinating depiction of a deeply human character.")
book3 = Book.create(title: "Icelandic Folklore and Fairytales", author_name: "Jon Arnason", image: File.open('app/assets/images/Icelandic_f_and__tales.jpg'))
book4 = Book.create(title: "Release It!", author_name: "Michael Nygard", image: File.open('app/assets/images/release_it.jpg'), blurb: "Whether it's in Java, .NET, or Ruby on Rails, getting your application ready to ship is only half the battle. Did you design your system to survivef a sudden rush of visitors from Digg or Slashdot? Or an influx of real world customers from 100 different countries? Are you ready for a world filled with flakey networks, tangled databases, and impatient users? If you're a developer and don't want to be on call for 3AM for the rest of your life, this book will help. In Release It!, Michael T. Nygard shows you how to design and architect your application for the harsh realities it will face. You'll learn how to design your application for maximum uptime, performance, and return on investment. Mike explains that many problems with systems today start with the design.")
book5 = Book.create(title: "SICP", author_name: "Gerald Jay Sussman and Hal Abelson", image: File.open('app/assets/images/SICP.jpg'), blurb: "Structure and Interpretation of Computer Programs has had a dramatic impact on computer science curricula over the past decade. This long-awaited revision contains changes throughout the text. There are new implementations of most of the major programming systems in the book, including the interpreters and compilers, and the authors have incorporated many small changes that reflect their experience teaching the course at MIT since the first edition was published. A new theme has been introduced that emphasizes the central role played by different approaches to dealing with time in computational models: objects with state, concurrent programming, functional programming and lazy evaluation, and nondeterministic programming. There are new example sections on higher-order procedures in graphics and on applications of stream processing in numerical programming, and many new exercises. In addition, all the programs have been reworked to run in any Scheme implementation that adheres to the IEEE standard.")
book6 = Book.create(title: "The Three Body Problem", author_name: "Cixin Liu", image: File.open('app/assets/images/three_body.jpg'), blurb: "The Three-Body Problem is the first chance for English-speaking readers to experience this multiple award winning phenomenon from China's most beloved science fiction author, Liu Cixin. Set against the backdrop of China's Cultural Revolution, a secret military project sends signals into space to establish contact with aliens. An alien civilization on the brink of destruction captures the signal and plans to invade Earth. Meanwhile, on Earth, different camps start forming, planning to either welcome the superior beings and help them take over a world seen as corrupt, or to fight against the invasion. The result is a science fiction masterpiece of enormous scope and vision.")
book7 = Book.create(title: "The Dark Forest", author_name: "Cixin Liu", image: File.open('app/assets/images/dark_forest.jpg'))
book8 = Book.create(title: "Apothegm of Diogenes", author_name: "Diogenes of Sinope", image: File.open('app/assets/images/default_book_cover.jpg'))
book9 = Book.create(title: "Independent People", author_name: "Haldor Laxness", image: File.open('app/assets/images/independent_peeps.jpg'))
book10 = Book.create(title: "Death's End", author_name: "Cixin Liu", image: File.open('app/assets/images/deaths_end.jpg'))
book11 = Book.create(title: "The Dwarf", author_name: "Pär Lagerkvist", image: File.open('app/assets/images/dwarf.jpg'))
book12 = Book.create(title: "Under the Glacier", author_name: "Haldor Laxness", image: File.open('app/assets/images/under_glacier.jpg'))
book13 = Book.create(title: "Flowers of Evil", author_name: "Charles Baudelaire", image: File.open('app/assets/images/flowers_of_evil.jpg'))
book14 = Book.create(title: "Táin Bó Cúailnge", author_name: "Lost to Antiquity", image: File.open('app/assets/images/tain.jpg'))
book15 = Book.create(title: "The Handmaid's Tale", author_name: "Margaret Atwood", image: File.open('app/assets/images/handmaid.jpg'))
book16 = Book.create(title: "The Left Hand of Darkness", author_name: "Ursula K. Le Guin", image: File.open('app/assets/images/left_hand.jpg'))
book17 = Book.create(title: "Discourses on Livy", author_name: "Nicolo Machiavelli", image: File.open('app/assets/images/livy.jpg'))
book18 = Book.create(title: "The Political Thought of William of Ockham", author_name: "Arthur Stephen McGrade", image: File.open('app/assets/images/ockham.jpg'))
book19 = Book.create(title: "Ramayana", author_name: "Vālmīki", image: File.open('app/assets/images/ramayana.jpg'))
book20 = Book.create(title: "Kural", author_name: "Thiruvalluvar", image: File.open('app/assets/images/kural.jpg'))
book21 = Book.create(title: "Aghora: At the Left Hand of God", author_name: "Robert E. Svoboda", image: File.open('app/assets/images/aghora.jpg'))
book23 = Book.create(title: "The Kalevala", author_name: "Elias Lönnrot", image: File.open('app/assets/images/kalevala.jpg'))
book24 = Book.create(title: "The Deeds of God in .Rddhipur", author_name: "Mhaimbhat", image: File.open('app/assets/images/deeds_of_god.jpg'))
book25 = Book.create(title: "Thinking, Fast and Slow", author_name: "Daniel Kahneman ", image: File.open('app/assets/images/fast_and_slow.jpg'))
book26 = Book.create(title: "Crossing of Prouerbs: Crosse-answeres and Crosse-humours", author_name: "Nicholas Breton", image: File.open('app/assets/images/cross_proverbs.jpg'))
book27 = Book.create(title: "Mahabharata", author_name: "Krishna-Dwaipayana Vyasa", image: File.open('app/assets/images/mahab.jpg'))
book28 = Book.create(title: "Heimskringla", author_name: "Snorri Sturluson", image: File.open('app/assets/images/heimskringla.jpg'))
book29 = Book.create(title: "The Mabinogi", author_name: "Lost to Antiquity", image: File.open('app/assets/images/mabinogi.jpg'))
book30 = Book.create(title: "Popol Vuh", author_name: "Lost to Antiquity", image: File.open('app/assets/images/popol.jpg'))
book31 = Book.create(title: "Dune", author_name: "Frank Herbert", image: File.open('app/assets/images/dune.jpg'))
book32 = Book.create(title: "American Gods", author_name: "Neil Gaiman", image: File.open('app/assets/images/american_gods.jpg'))
book33 = Book.create(title: "Rakshasa's Ring", author_name: "Viśākhadatta ", image: File.open('app/assets/images/rakshasa.jpg'))
book34 = Book.create(title: "Cain", author_name: "José Saramago", image: File.open('app/assets/images/cain.jpg'))
book35 = Book.create(title: "My Struggle: Book 1", author_name: "Karl Ove Knausgård", image: File.open('app/assets/images/struggle.jpg'))
book36 = Book.create(title: "We Have Always Lived in the Castle", author_name: "Shirley Jackson", image: File.open('app/assets/images/castle.jpg'))
book37 = Book.create(title: "The Legitimacy of the Modern Age", author_name: "Hans Blumenberg", image: File.open('app/assets/images/legitimacy.jpg'))
book38 = Book.create(title: "Between Facts & Norms", author_name: "Jürgen Habermas", image: File.open('app/assets/images/facts_and_norms.jpg'))
book39 = Book.create(title: "The Political Forms of Modern Society: Bureaucracy, Democracy, Totalitarianism", author_name: "Claude Lefort", image: File.open('app/assets/images/political_forms.jpg'))
book40 = Book.create(title: "Economy and Society: An Outline of Interpretive Sociology", author_name: "Max Weber", image: File.open('app/assets/images/e_and_s.jpg'))
book41 = Book.create(title: "All the King's Men", author_name: "Robert Penn Warren", image: File.open('app/assets/images/jack_burden.jpg'))
book42 = Book.create(title: "The Infinity Gauntlet ", author_name: "Jim Starlin", image: File.open('app/assets/images/infinity.jpg'))
book43 = Book.create(title: "The Silmarillion", author_name: "J. R. R. Tolkein", image: File.open('app/assets/images/Silmarillion.jpg'))
book44 = Book.create(title: "Neuromancer", author_name: "William Gibson", image: File.open('app/assets/images/neuromancer.jpg'))
book45 = Book.create(title: "Labyrinths: Selected Stories and Other Writings", author_name: "Jorge Luis Borges", image: File.open('app/assets/images/Labyrinths.jpg'))
book46 = Book.create(title: "The Old Man and the Sea", author_name: "Ernest Hemingway", image: File.open('app/assets/images/old_man.jpg'))
book47 = Book.create(title: "Immortal Lycanthropes", author_name: "Hal Johnson", image: File.open('app/assets/images/imortal.jpg'))
book48 = Book.create(title: "The Plague", author_name: "Albert Camus", image: File.open('app/assets/images/plague.jpg'))
book49 = Book.create(title: "Moby Dick", author_name: "Herman Melville", image: File.open('app/assets/images/moby_dick.jpg'))
book50 = Book.create(title: "Fearsome Creatures of the Lumberwoods: Twenty Chilling Tales from the Wilderness", author_name: "Hal Johnson", image: File.open('app/assets/images/fearsome.jpg'))

Review.destroy_all
review1 = Review.create(book_id: book1.id, user_id: user1.id, title: "Sagely wisdom", body: "He's no Solomon, but the sayings of Odin have some pretty good gems.  Not the best telling of the Volsunga saga I've read.")
review2 = Review.create(book_id: book1.id, user_id: user2.id, title: "I love the norse", body: "Title says it all")
review2 = Review.create(book_id: book2.id, user_id: user2.id, title: "I'm sorry; it's gross", body: "Gutter humor all the way down.  Don't get me wrong, it's very clever gutter humor.  Still, ick.")
review3 = Review.create(book_id: book2.id, user_id: user1.id, title: "My favorite Saga", body: "Seriously -- it's like someone wed Diogenes of Sinope and 80's action movie hero, wrapping the whole thing in the trappings of the medieval bardic tradition.  Everyone should read this book, and everyone should love this book.")
review4 = Review.create(book_id: book2.id, user_id: user5.id, title: "Good jokes by a bad poet", body: "Look, I get why Mike like this book so much.  I don't think it's the best, though.  It's up there.  One of the best.  But, Njal's is so much better.  4 out of 4 Barn's agree.")
review5 = Review.create(book_id: book14.id, user_id: user1.id, title: "A fun adventure", body: "There are some classic adventure tropes here.  I guess what I like most about this is how low the stakes are.  The whole thing is written with this epic scope, but it's just some guys stealing cows from their neighbors.  I mean, there's something humerous in that, right?")
review6 = Review.create(book_id: book14.id, user_id: user2.id, title: "Great pictures", body: "Man, this edition has some wonderful pictures.")
review7 = Review.create(book_id: book14.id, user_id: user6.id, title: "Maeve is awesome", body: "Seriously powerful woman queen starting (local) international incidents because her pride has been insulted.")
review8 = Review.create(book_id: book11.id, user_id: user1.id, title: "Ugh", body: "I like stories about the machinations of spiteful dwarves and the power they influence over kings as much as the next, but this is a little too close to home right now.")
review9 = Review.create(book_id: book11.id, user_id: user2.id, title: "Meh", body: "It was fine.")
review10 = Review.create(book_id: book11.id, user_id: user5.id, title: "What a weird book.", body: "Don't get me wrong, I think I like it.  I recommended it to a friend.  I just don't know why I like it.  It's so weird.")
review11 = Review.create(book_id: book4.id, user_id: user1.id, title: "Thanks, DM!", body: "I was building a rails app for a colleague and encountered a nasty race condition.  I complained about it to my spouse, and she talked to her boss who recommended this book to me.  Man, what a wonderful discussion of design practices, and the rationale behind them.  Clear and measured throughout.  I feel like I leveld up after reading this book.  Thanks, David!")
review12 = Review.create(book_id: book2.id, user_id: user3.id, title: "Boys!", body: "Why did I let myself get roped into reading this garbage.  I mean, they told me it was about a viking.  They way they talked about it didn't make it sound appeaing either.  But, they just wouldn't shut up.  So, I gave it a go.  I regret that.")
review13 = Review.create(book_id: book5.id, user_id: user6.id, title: "Lorem", body: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.")
review14 = Review.create(book_id: book5.id, user_id: user2.id, title: "Mathmatical!", body: "What a lovely introduction.  I enjoy the enthusiasm these two clearly have for the subject, and the wishful thinking approach to breaking down problems is really cool.  I did watch the lectures along with this book.  P.S. -- knowing Z, I'll bet she typed out that Lorem Ipsum herself!")
review15 = Review.create(book_id: book44.id, user_id: user1.id, title: "classic", body: "One weird thing, though -- the future as Gibson envisioned it was really pink.  Read the book again -- 82 times he says pink.  It's just pink plastic bubblegum.  It's vaporwave.")
review16 = Review.create(book_id: book44.id, user_id: user2.id, title: "Meh", body: "It's fine.  Overrated")
review17 = Review.create(book_id: book44.id, user_id: user3.id, title: "I agree with that guy!", body: "It's an okay book.  But, a bit boring.")
review18 = Review.create(book_id: book44.id, user_id: user4.id, title: "Woof!", body: "I'm a dog!  I don't read!  Who gave me an account.  Bark Bark Bark!  I don't like when my family reads--Let's go throw the toy around.")
review19 = Review.create(book_id: book44.id, user_id: user5.id, title: "It was a part of my childhood", body: "I can't judge it properly, but I am sad to see the extent to which Gibson got the future right.")
review20 = Review.create(book_id: book6.id, user_id: user6.id, title: "Hugo and Nebula in translation FTW", body: "This completely deserved to win both of these awards.  Amazing book.")
review20 = Review.create(book_id: book7.id, user_id: user2.id, title: "Game Theory", body: "One of the most innovative applications of game theory in modern Sci-Fi.")
review20 = Review.create(book_id: book7.id, user_id: user3.id, title: "Solid follow-up", body: "I didn't like it quite as much as the original, but I'm still in it for the long haul.")
review20 = Review.create(book_id: book7.id, user_id: user4.id, title: "It's a book", body: "I read it.  I'll read the next one.")
review20 = Review.create(book_id: book7.id, user_id: user6.id, title: "Too cynical", body: "The despairing view of the universe as a dark forest governed by mutual suspicion and a base drive to survive is bleak, and the author knows it.  At the same time, he doesn't seem to appreceate the possibility of beautiful actions, and meaning residing in that beauty itself.  He thinks that at the level of the species such actions are erradicated, and this is dreaful and despairing.")
review20 = Review.create(book_id: book8.id, user_id: user1.id, title: "A true hero", body: "Our modern age could take a lot from the wisdom of this 'dog.'  His insistence on frank speech and truth-telling could server our culture well. ")
review20 = Review.create(book_id: book8.id, user_id: user3.id, title: "What a jokester", body: "I know that most of the stories we have about this guy are just fabrications, but what fabrications!  A better troll than anyone on the internet today, and he did it with a purpose--to help others rather than to hurt them.  What a guy.")
review20 = Review.create(book_id: book8.id, user_id: user4.id, title: "No Cover", body: "I guess Diogenes himself would have scorned the cover of a book, so it's appropriate that this entry doesn't have one.")
review20 = Review.create(book_id: book9.id, user_id: user6.id, title: "I will date none who have not read this book.", body: "It is impossible to be cultured without knowing about Haldor.")
review20 = Review.create(book_id: book9.id, user_id: user2.id, title: "Good, not great.", body: "Not his best work.  Check out Under the Glaciar.")
review20 = Review.create(book_id: book9.id, user_id: user3.id, title: "Disturbing at places", body: "I like how he doesn't look down upon the 'salt of the earth' when writing about them.  Still, there are some very uncomfortable father-daughter moments.  Nice to see strong women in western world literature.")
review20 = Review.create(book_id: book10.id, user_id: user2.id, title: "Mind Blown", body: "It's like a Summa Science-fictionica.  Every 20 pages my mind was blown.  Also, the best possible (but still inadequate) secular response to the question of good and evil.  This guy is a modern Dostoyevsky.")
review20 = Review.create(book_id: book10.id, user_id: user3.id, title: "Best of the three", body: "Glad I stuck in for the long haul.  It was worth it.")
review20 = Review.create(book_id: book10.id, user_id: user4.id, title: "Aesthetic morality", body: "Like all intelligent folk who have inquired into the subject and not been driving mad or to nihilism, Cixin understands that rationality cannot render the world of this life meaningful.  The best rationality gets you is the bleak world of The Dark Forest.  Only an asethetic response will do.")
review20 = Review.create(book_id: book10.id, user_id: user5.id, title: "huh!", body: "Rarely does a book that addresses such weighty issues read so lightly!")
review20 = Review.create(book_id: book10.id, user_id: user6.id, title: "Not just Si Fi, it's true literature", body: "This book should get more press.  It could breath life back into the genre.")
review20 = Review.create(book_id: book11.id, user_id: user3.id, title: "Terrifying musings on human nature in the wake of the second world war", body: "I hope Par is wrong.")
review20 = Review.create(book_id: book11.id, user_id: user4.id, title: "I don't get it.", body: "I have been defeated.  I have friends that don't understand Scandenavian literature, and I pride myself in distinguishing myself from them.  That said, this book has vanquished me.  I just don't get it .  Why was it written.  What's the point and what's the message?")
review20 = Review.create(book_id: book12.id, user_id: user3.id, title: "Not his best", body: "Check out Indpendent People if you really want to understand this guy's reputation.")
review20 = Review.create(book_id: book12.id, user_id: user4.id, title: "My favorite", body: "The ghosts!")
review20 = Review.create(book_id: book12.id, user_id: user5.id, title: "Great jokes", body: "Funny dude.")
review20 = Review.create(book_id: book12.id, user_id: user6.id, title: "His crowning achievement", body: "This work balances perfectly Iceland's own trouble relationship with its pagan and christian heritage with references to the sagas, pastors dealing with questions of faith, real theological questions, and all with a great dollop of humor.  This is the work of a master of the craft at his prime.")
review20 = Review.create(book_id: book13.id, user_id: user3.id, title: "I like that he can find beauty in ugliness", body: "I mean, this guy is clearly getting some perverse pleasure out of subverting cultural norms, but it's still a good message.  We should look for beauty everywhere, and not reject anything or anyone.")
review20 = Review.create(book_id: book13.id, user_id: user4.id, title: "Gross", body: "This book should be banned.")
review20 = Review.create(book_id: book13.id, user_id: user5.id, title: "The first book of poetry I loved", body: "I didn't understand poetry until reading this.  Sure, I was a sullen teenager, but it opened my eyes to a bueauty I hadn't understood before.  Fin de siècle waas the best time.")
review20 = Review.create(book_id: book13.id, user_id: user6.id, title: "Warms my goth heart", body: "Chuck B was goth before goth was goth.")
review20 = Review.create(book_id: book14.id, user_id: user3.id, title: "Bridge between folklore and mythology", body: "It is really cool to see a longer tale, one tied up with the greater mythology of a people, incorperate so many trops from folklore.  This is a genre straddling work of the best sort.")
review20 = Review.create(book_id: book14.id, user_id: user4.id, title: "Interesting", body: "It's a book that has kind of a gross traditional depiction of 'manliness' sitting alongside very powerful women who are not vilified.  It's nice to see that these things are not mutually antagonistic.")
review20 = Review.create(book_id: book14.id, user_id: user5.id, title: "Woo!", body: "Heros that jump!")
review20 = Review.create(book_id: book15.id, user_id: user2.id, title: "Unrealistic", body: "We're not that awful, are we?  Could we ever really stoop this low?")
review20 = Review.create(book_id: book15.id, user_id: user3.id, title: "Scary", body: "Sometimes I feel like this is closer to reality than everyone would like to think.")
review20 = Review.create(book_id: book15.id, user_id: user4.id, title: "Distopian Literature at its best", body: "Distopian literature ought not to be what it has become.  Rather than simply describing a dark world, it ought to shine a light on trends in our current world that, if allowed to grow, could lead to disasterous consequences.  Gibson and Atwood both do this.  Kids these days, with their \"I'm Hungry Games\" do NOT know what they are missing.")




ReadStatus.destroy_all
readstatus1 = ReadStatus.create(user_id: user1.id, book_id:book1.id, status:"read")
readstatus2 = ReadStatus.create(user_id: user1.id, book_id:book2.id, status:"read")
readstatus3 = ReadStatus.create(user_id: user1.id, book_id:book3.id, status:"read")
readstatus4 = ReadStatus.create(user_id: user1.id, book_id:book4.id, status:"read")
readstatus5 = ReadStatus.create(user_id: user1.id, book_id:book5.id, status:"read")
readstatus6 = ReadStatus.create(user_id: user1.id, book_id:book6.id, status:"read")
readstatus7 = ReadStatus.create(user_id: user1.id, book_id:book7.id, status:"read")
readstatus8 = ReadStatus.create(user_id: user1.id, book_id:book8.id, status:"read")
readstatus9 = ReadStatus.create(user_id: user1.id, book_id:book9.id, status:"read")
readstatus10 = ReadStatus.create(user_id: user1.id, book_id:book10.id, status:"reading")
readstatus11 = ReadStatus.create(user_id: user1.id, book_id:book11.id, status:"reading")
readstatus12 = ReadStatus.create(user_id: user1.id, book_id:book12.id, status:"reading")
readstatus13 = ReadStatus.create(user_id: user1.id, book_id:book13.id, status:"reading")
readstatus14 = ReadStatus.create(user_id: user1.id, book_id:book14.id, status:"reading")
readstatus15 = ReadStatus.create(user_id: user1.id, book_id:book15.id, status:"to-read")
readstatus16 = ReadStatus.create(user_id: user1.id, book_id:book17.id, status:"to-read")
readstatus19 = ReadStatus.create(user_id: user5.id, book_id:book6.id, status:"reading")
readstatus20 = ReadStatus.create(user_id: user6.id, book_id:book15.id, status:"read")
readstatus21 = ReadStatus.create(user_id: user6.id, book_id:book4.id, status:"to-read")
readstatus22 = ReadStatus.create(user_id: user1.id, book_id:book5.id, status:"to-read")
readstatus23 = ReadStatus.create(user_id: user2.id, book_id:book13.id, status:"reading")
readstatus24 = ReadStatus.create(user_id: user2.id, book_id:book6.id, status:"read")
readstatus25 = ReadStatus.create(user_id: user2.id, book_id:book7.id, status:"reading")
readstatus26 = ReadStatus.create(user_id: user2.id, book_id:book10.id, status:"to-read")
readstatus27 = ReadStatus.create(user_id: user5.id, book_id:book1.id, status:"read")
readstatus28 = ReadStatus.create(user_id: user5.id, book_id:book2.id, status:"read")
readstatus29 = ReadStatus.create(user_id: user5.id, book_id:book12.id, status:"read")
readstatus30 = ReadStatus.create(user_id: user1.id, book_id:book18.id, status:"to-read")
readstatus31 = ReadStatus.create(user_id: user1.id, book_id:book19.id, status:"to-read")
readstatus32 = ReadStatus.create(user_id: user1.id, book_id:book20.id, status:"to-read")
readstatus33 = ReadStatus.create(user_id: user1.id, book_id:book21.id, status:"to-read")
readstatus35 = ReadStatus.create(user_id: user1.id, book_id:book23.id, status:"to-read")
readstatus36 = ReadStatus.create(user_id: user1.id, book_id:book24.id, status:"to-read")
readstatus37 = ReadStatus.create(user_id: user1.id, book_id:book25.id, status:"to-read")
readstatus38 = ReadStatus.create(user_id: user1.id, book_id:book26.id, status:"to-read")
readstatus39 = ReadStatus.create(user_id: user1.id, book_id:book27.id, status:"to-read")
readstatus40 = ReadStatus.create(user_id: user1.id, book_id:book28.id, status:"to-read")
readstatus41 = ReadStatus.create(user_id: user1.id, book_id:book29.id, status:"to-read")
readstatus42 = ReadStatus.create(user_id: user5.id, book_id:book8.id, status:"to-read")
readstatus43 = ReadStatus.create(user_id: user6.id, book_id:book8.id, status:"to-read")

Shelf.destroy_all
shelf1 = Shelf.create(user_id: user1.id, title: "Philosophy")
shelf2 = Shelf.create(user_id: user1.id, title: "IT")
shelf3 = Shelf.create(user_id: user1.id, title: "Sci-Fi")
shelf4 = Shelf.create(user_id: user1.id, title: "Iceland")
shelf5 = Shelf.create(user_id: user1.id, title: "Mythology")
shelf6 = Shelf.create(user_id: user1.id, title: "American")
shelf7 = Shelf.create(user_id: user1.id, title: "Poetry")
shelf8 = Shelf.create(user_id: user1.id, title: "Friends")
shelf9 = Shelf.create(user_id: user5.id, title: "music biography")
shelf10 = Shelf.create(user_id: user5.id, title: "nobels")
shelf17 = Shelf.create(user_id: user5.id, title: "Iceland" )
shelf18 = Shelf.create(user_id: user6.id, title: "Gothic Literature")
shelf19 = Shelf.create(user_id: user6.id, title: "Celtic Reconstruction")
shelf20 = Shelf.create(user_id: user6.id, title: "Feminist Literature")

ShelvedBook.destroy_all
shelvedbook1 = ShelvedBook.create(book_id: book17.id, shelf_id: shelf1.id)
shelvedbook1 = ShelvedBook.create(book_id: book18.id, shelf_id: shelf1.id)
shelvedbook1 = ShelvedBook.create(book_id: book38.id, shelf_id: shelf1.id)
shelvedbook1 = ShelvedBook.create(book_id: book39.id, shelf_id: shelf1.id)
shelvedbook1 = ShelvedBook.create(book_id: book40.id, shelf_id: shelf1.id)
shelvedbook1 = ShelvedBook.create(book_id: book1.id, shelf_id: shelf1.id)
shelvedbook4 = ShelvedBook.create(book_id: book2.id, shelf_id: shelf7.id)
shelvedbook5 = ShelvedBook.create(book_id: book3.id, shelf_id: shelf4.id)
shelvedbook6 = ShelvedBook.create(book_id: book4.id, shelf_id: shelf2.id)
shelvedbook7 = ShelvedBook.create(book_id: book5.id, shelf_id: shelf2.id)
shelvedbook8 = ShelvedBook.create(book_id: book6.id, shelf_id: shelf3.id)
shelvedbook9 = ShelvedBook.create(book_id: book7.id, shelf_id: shelf3.id)
shelvedbook10 = ShelvedBook.create(book_id: book10.id, shelf_id: shelf3.id)
shelvedbook11 = ShelvedBook.create(book_id: book8.id, shelf_id: shelf1.id)
shelvedbook12 = ShelvedBook.create(book_id: book9.id, shelf_id: shelf4.id)
shelvedbook15 = ShelvedBook.create(book_id: book12.id, shelf_id: shelf4.id)
shelvedbook17 = ShelvedBook.create(book_id: book14.id, shelf_id: shelf9.id)
shelvedbook18 = ShelvedBook.create(book_id: book15.id, shelf_id: shelf10.id)
shelvedbook18 = ShelvedBook.create(book_id: book16.id, shelf_id: shelf10.id)
shelvedbook18 = ShelvedBook.create(book_id: book16.id, shelf_id: shelf3.id)
shelvedbook18 = ShelvedBook.create(book_id: book31.id, shelf_id: shelf3.id)
shelvedbook18 = ShelvedBook.create(book_id: book44.id, shelf_id: shelf3.id)
shelvedbook15 = ShelvedBook.create(book_id: book1.id, shelf_id: shelf4.id)
shelvedbook15 = ShelvedBook.create(book_id: book2.id, shelf_id: shelf4.id)
shelvedbook15 = ShelvedBook.create(book_id: book1.id, shelf_id: shelf5.id)
shelvedbook15 = ShelvedBook.create(book_id: book2.id, shelf_id: shelf5.id)
shelvedbook15 = ShelvedBook.create(book_id: book3.id, shelf_id: shelf5.id)
shelvedbook15 = ShelvedBook.create(book_id: book14.id, shelf_id: shelf5.id)
shelvedbook15 = ShelvedBook.create(book_id: book23.id, shelf_id: shelf5.id)
shelvedbook15 = ShelvedBook.create(book_id: book24.id, shelf_id: shelf5.id)
shelvedbook15 = ShelvedBook.create(book_id: book27.id, shelf_id: shelf5.id)
shelvedbook15 = ShelvedBook.create(book_id: book28.id, shelf_id: shelf5.id)
shelvedbook15 = ShelvedBook.create(book_id: book29.id, shelf_id: shelf5.id)
shelvedbook15 = ShelvedBook.create(book_id: book30.id, shelf_id: shelf5.id)
shelvedbook15 = ShelvedBook.create(book_id: book43.id, shelf_id: shelf5.id)
shelvedbook15 = ShelvedBook.create(book_id: book31.id, shelf_id: shelf6.id)
shelvedbook15 = ShelvedBook.create(book_id: book32.id, shelf_id: shelf6.id)
shelvedbook15 = ShelvedBook.create(book_id: book36.id, shelf_id: shelf6.id)
shelvedbook15 = ShelvedBook.create(book_id: book41.id, shelf_id: shelf6.id)
shelvedbook15 = ShelvedBook.create(book_id: book46.id, shelf_id: shelf6.id)
shelvedbook15 = ShelvedBook.create(book_id: book49.id, shelf_id: shelf6.id)
shelvedbook15 = ShelvedBook.create(book_id: book20.id, shelf_id: shelf7.id)
shelvedbook15 = ShelvedBook.create(book_id: book23.id, shelf_id: shelf7.id)
shelvedbook15 = ShelvedBook.create(book_id: book13.id, shelf_id: shelf7.id)
shelvedbook15 = ShelvedBook.create(book_id: book47.id, shelf_id: shelf8.id)
shelvedbook15 = ShelvedBook.create(book_id: book50.id, shelf_id: shelf8.id)
